IF (SPR_LIBRARIES)
  SET (SPR_FIND_QUIETLY TRUE)
ENDIF (SPR_LIBRARIES)

IF (SPR_USE_INT8)
  SET (LIBNAME SPR_I8)
ELSE (SPR_USE_INT8)
  SET (LIBNAME SPR)
ENDIF (SPR_USE_INT8)

FIND_LIBRARY(SPR_LIBRARIES
  NAMES ${LIBNAME}
  PATHS $ENV{HOME}/lib $ENV{HOME}/.local/lib /usr/local/lib
)

MARK_AS_ADVANCED(SPR_LIBRARIES)

IF (SPR_LIBRARIES)
  FIND_LIBRARY(ASM_LIBRARIES
    NAMES ASM SAM
    PATHS $ENV{HOME}/lib $ENV{HOME}/.local/lib /usr/local/lib
  )
  IF (ASM_LIBRARIES)
    SET (SPR_LIBRARIES ${SPR_LIBRARIES} ${ASM_LIBRARIES})
  ENDIF (ASM_LIBRARIES)
  MARK_AS_ADVANCED(ASM_LIBRARIES)
ENDIF (SPR_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SPR DEFAULT_MSG SPR_LIBRARIES)
