IF (SPR_LIBRARIES)
  SET (SPR_FIND_QUIETLY TRUE)
ENDIF (SPR_LIBRARIES)

FIND_LIBRARY(SPR_LIBRARIES
  NAMES SPR
  PATHS $ENV{HOME}/lib
  /sima/libs/SAM
)

IF (SPR_LIBRARIES)
  FIND_LIBRARY(ASM_LIBRARIES
    NAMES ASM
    PATHS $ENV{HOME}/lib
    /sima/libs/SAM
  )
  IF (ASM_LIBRARIES)
    SET (SPR_LIBRARIES ${SPR_LIBRARIES} ${ASM_LIBRARIES})
  ENDIF (ASM_LIBRARIES)
ENDIF (SPR_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SPR DEFAULT_MSG
                                  SPR_LIBRARIES)

MARK_AS_ADVANCED(SPR_LIBRARIES)
