find_package(PkgConfig)

set(OLD_PKG $ENV{PKG_CONFIG_PATH})
set(ENV{PKG_CONFIG_PATH} $ENV{PETSC_DIR}/$ENV{PETSC_ARCH}/lib/pkgconfig)
pkg_check_modules(ISTL dune-istl)
pkg_check_modules(ISTLc dune-common)
list(APPEND ISTL_LIBRARIES ${ISTLc_LIBRARIES})
set(ENV{PKG_CONFIG_PATH} ${OLD_PKG})

list(APPEND ISTL_DEFINITIONS -DHAVE_NULLPTR=1 -DISTL_VERSION="${ISTL_VERSION}")
string(REPLACE "." ";" VERSION_LIST "${ISTL_VERSION}")
if(VERSION_LIST)
  list(GET VERSION_LIST 0 DUNE_ISTL_VERSION_MAJOR)
  list(GET VERSION_LIST 1 DUNE_ISTL_VERSION_MINOR)
  list(LENGTH VERSION_LIST nver)
  if(nver GREATER 2)
    list(GET VERSION_LIST 2 DUNE_ISTL_VERSION_PATCH)
  else()
    set(DUNE_ISTL_VERSION_PATCH 0)
  endif()
  list(APPEND ISTL_DEFINITIONS -DDUNE_ISTL_VERSION_MAJOR=${DUNE_ISTL_VERSION_MAJOR}
                               -DDUNE_ISTL_VERSION_MINOR=${DUNE_ISTL_VERSION_MINOR}
                               -DDUNE_ISTL_VERSION_REVISION=${DUNE_ISTL_VERSION_PATCH})
endif()

if(SUPERLU_FOUND)
  list(APPEND ISTL_DEFINITIONS -DHAVE_SUPERLU=1 -DSUPERLU_POST_2005_VERSION=1 -DSUPERLU_NTYPE=1 -DSUPERLU_MIN_VERSION_4_3=1 -DSUPERLU_INT_TYPE=int)
  if (HAVE_SUPERLU_5)
    list(APPEND ISTL_DEFINITIONS -DSUPERLU_MIN_VERSION_5=1)
  endif()
endif()

if(SuiteSparse_UMFPACK_FOUND AND ISTL_FOUND)
  list(APPEND ISTL_DEFINITIONS -DHAVE_UMFPACK=1 -DHAVE_SUITESPARSE_UMFPACK=1)
  list(APPEND ISTL_INCLUDE_DIRS ${UMFPACK_INCLUDE_DIR})
  list(APPEND ISTL_LIBRARIES ${UMFPACK_LIBRARY})
endif()

list(APPEND ISTL_INCLUDE_DIRS ${ISTL_INCLUDEDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ISTL DEFAULT_MSG
                                  ISTL_INCLUDE_DIRS ISTL_LIBRARIES)
