IFEM: ASM::InterfaceChecker Class Reference
ASM::InterfaceChecker Class Reference abstract
Base class to check for internal boundary integrand contributions.
#include <Interface.h>
Public Member Functions
virtual ~InterfaceChecker ()=default
Default destructor.
virtual short int hasContribution (int iel, int I, int J, int K=-1) const =0
Returns non-zero if the specified element has contributions.
virtual short int elmBorderMask (double u0, double u1, double v0, double v1, double w0=0.0, double w1=1.0) const
Returns a status mask based on the element boundary parameters.
Detailed Description
Base class to check for internal boundary integrand contributions.
Member Function Documentation
elmBorderMask()
virtual short int ASM::InterfaceChecker::elmBorderMask (double u0, double u1, double v0, double v1, double w0 = 0.0, double w1 = 1.0) const inline virtual
Returns a status mask based on the element boundary parameters.
Parameters
[in] u0 Parameter value of the west element boundary
[in] u1 Parameter value of the east element boundary
[in] v0 Parameter value of the south element boundary
[in] v1 Parameter value of the north element boundary
[in] w0 Parameter value of the back element boundary
[in] w1 Parameter value of the front element boundary
Referenced by ASMs2D::integrate(), and ASMu2D::integrate().
hasContribution()
virtual short int ASM::InterfaceChecker::hasContribution (int iel, int I, int J, int K = -1) const pure virtual
Returns non-zero if the specified element has contributions.
Parameters
[in] iel Element number
[in] I Index in first parameter direction of the element
[in] J Index in second parameter direction of the element
[in] K Index in third parameter direction of the element
Implemented in ASMs2DIB::Intersected, ASMs2D::InterfaceChecker, ASMs3D::InterfaceChecker, and ASMu2D::InterfaceChecker.
Referenced by ASMs2D::addInterfaceElms(), ASMs2D::integrate(), ASMs2Dmx::integrate(), and ASMs3Dmx::integrate().
The documentation for this class was generated from the following file:
src/ASM/Interface.h