IFEM: GaussQuadrature Class Reference
GaussQuadrature Class Reference
Gaussian quadrature rules in one dimension.
#include <GaussQuadrature.h>
Static Public Member Functions
static const double * getCoord (int n)
Get gauss point coordinates in the domain [-1,1].
static const double * getWeight (int n)
Get gauss point weights.
Static Private Member Functions
static const double * getGauss (int n, int i)
Returns the gauss point coordinates or weights.
Detailed Description
Gaussian quadrature rules in one dimension.
Member Function Documentation
getCoord()
static const double* GaussQuadrature::getCoord (int n) inline static
Get gauss point coordinates in the domain [-1,1].
Parameters
[in] n Number of gauss points
References getGauss().
Referenced by ASMs1D::assembleL2matrices(), ASMs2D::assembleL2matrices(), ASMs3D::assembleL2matrices(), ASMu2D::assembleL2matrices(), ASMu3D::assembleL2matrices(), ASMu2D::edgeL2projection(), ASMu3D::faceL2projection(), Immersed::getQuadraturePoints(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs3D::integrateEdge(), ASMs3DLag::integrateEdge(), ASMs2D::projectSolutionLeastSquare(), ASMs3D::projectSolutionLeastSquare(), ASMs2D::scRecovery(), ASMu2D::scRecovery(), ASMu3D::scRecovery(), ASMs2D::BasisFunctionCache::setupQuadrature(), ASMs3D::BasisFunctionCache::setupQuadrature(), ASMu2D::BasisFunctionCache::setupQuadrature(), and ASMu3D::BasisFunctionCache::setupQuadrature().
getGauss()
const double * GaussQuadrature::getGauss (int n, int i) static private
Returns the gauss point coordinates or weights.
Parameters
[in] n Number of gauss points
[in] i Option telling what to return (0=coordinates, 1=weights)
References G1, G10, G2, G3, G4, G5, G6, G7, G8, and G9.
Referenced by getCoord(), and getWeight().
getWeight()
static const double* GaussQuadrature::getWeight (int n) inline static
Get gauss point weights.
Parameters
[in] n Number of gauss points
References getGauss().
Referenced by ASMs1D::assembleL2matrices(), ASMs2D::assembleL2matrices(), ASMs3D::assembleL2matrices(), ASMu2D::assembleL2matrices(), ASMu3D::assembleL2matrices(), ASMu2D::edgeL2projection(), ASMu3D::faceL2projection(), Immersed::getQuadraturePoints(), ASMs1D::integrate(), ASMs1DLag::integrate(), ASMs2D::integrate(), ASMs2DLag::integrate(), ASMs2Dmx::integrate(), ASMs2DmxLag::integrate(), ASMs2DTri::integrate(), ASMs3D::integrate(), ASMs3DLag::integrate(), ASMs3Dmx::integrate(), ASMs3DmxLag::integrate(), ASMu2D::integrate(), ASMu2Dmx::integrate(), ASMu3D::integrate(), ASMu3Dmx::integrate(), ASMs3D::integrateEdge(), ASMs3DLag::integrateEdge(), ASMs2D::projectSolutionLeastSquare(), ASMs3D::projectSolutionLeastSquare(), ASMs2D::BasisFunctionCache::setupQuadrature(), ASMs3D::BasisFunctionCache::setupQuadrature(), ASMu2D::BasisFunctionCache::setupQuadrature(), and ASMu3D::BasisFunctionCache::setupQuadrature().
The documentation for this class was generated from the following files:
src/Utility/GaussQuadrature.h
src/Utility/GaussQuadrature.C