IFEM: NodalConstraintASMs3DHelper Class Reference
NodalConstraintASMs3DHelper Class Reference
Helper for apply constraints to a structured 3D model.
Public Member Functions
NodalConstraintASMs3DHelper (ASMs3D *pch)
The constructor forwards to the parent class constructor.
virtual int getCorner (int vertex, int basis) const
Returns the local node number of a given corner of the patch.
virtual void constrainEdge (int item, int comp, int basis, int idx)
Constrains a given edge to a given node.
virtual void constrainFace (int item, int comp, int basis, int idx)
Constrains a given face to a given node.
Public Member Functions inherited from NodalConstraintASMHelper
NodalConstraintASMHelper (ASMbase *pch)
The constructor initializes the patch pointer.
virtual ~NodalConstraintASMHelper ()
Empty destructor.
void constrainVertex (int item, int comp, int basis, int idx)
Constrains a given vertex to a given node.
void constrainPatch (int comp, int basis, int idx)
Constrains the whole patch to a given node.
Additional Inherited Members
Protected Member Functions inherited from NodalConstraintASMHelper
void constrainNode (int item, int comp, int idx)
Constrains a given node to another node.
int getStartNode (int basis) const
Returns the starting node for the given basis.
Protected Attributes inherited from NodalConstraintASMHelper
ASMbase * bpch
Pointer to the associated patch.
Detailed Description
Helper for apply constraints to a structured 3D model.
Member Function Documentation
constrainEdge()
virtual void NodalConstraintASMs3DHelper::constrainEdge (int item, int comp, int basis, int idx) inline virtual
Constrains a given edge to a given node.
Parameters
[in] item Edge index on patch
[in] comp Component to constrain
[in] basis Basis to constrain edge for
[in] idx Global node to constrain edge to
Reimplemented from NodalConstraintASMHelper.
References NodalConstraintASMHelper::bpch, NodalConstraintASMHelper::constrainNode(), and NodalConstraintASMHelper::getStartNode().
Referenced by SIMNodalConstraint< Dim >::applyConstraint().
constrainFace()
virtual void NodalConstraintASMs3DHelper::constrainFace (int item, int comp, int basis, int idx) inline virtual
Constrains a given face to a given node.
Parameters
[in] item Face index on patch
[in] comp Component to constrain
[in] basis Basis to constrain face for
[in] idx Global node to constrain face to
Reimplemented from NodalConstraintASMHelper.
References NodalConstraintASMHelper::bpch, NodalConstraintASMHelper::constrainNode(), and NodalConstraintASMHelper::getStartNode().
Referenced by SIMNodalConstraint< Dim >::applyConstraint().
getCorner()
virtual int NodalConstraintASMs3DHelper::getCorner (int vertex, int basis) const inline virtual
Returns the local node number of a given corner of the patch.
Parameters
[in] vertex Vertex index to return the node number for
[in] basis Basis for vertex
Implements NodalConstraintASMHelper.
References NodalConstraintASMHelper::bpch, ASMbase::getNodeID(), and NodalConstraintASMHelper::getStartNode().
Referenced by SIMNodalConstraint< Dim >::applyConstraint().
The documentation for this class was generated from the following file:
Apps/Common/SIMNodalConstraint.C