IFEM: TimeIntegration::SIMExplicitRK< Solver > Class Template Reference
TimeIntegration::SIMExplicitRK< Solver > Class Template Reference
Explicit Runge-Kutta based time stepping for SIM classes.
#include <SIMExplicitRK.h>
Public Member Functions
SIMExplicitRK (Solver &solv, Method type, bool standalone=true)
Constructor.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
virtual bool solveStep (TimeStep &tp)
Computes the solution for the current time step.
bool solveRK (Vectors &stages, const TimeStep &tp)
Applies the Runge-Kutta scheme.
bool advanceStep (TimeStep &tp)
Advances the time step one step forward.
bool saveModel (char *fileName, int &geoBlk, int &nBlock)
Opens a new VTF-file and writes the model geometry to it.
bool saveStep (const TimeStep &tp, int &nBlock)
Saves the converged results of a given time step to VTF file.
void registerFields (DataExporter &exporter)
Registers fields for output to a data exporter.
bool serialize (std::map< std::string, std::string > &data)
Serialize internal state for restarting purposes.
bool deSerialize (const std::map< std::string, std::string > &data)
Set internal state from a serialized state.
void setLinear (bool enable)
Mark operator as linear to avoid repeated assembly and factorization.
Protected Attributes
Solver & solver
Reference to simulator.
RKTableaux RK
Tableaux of Runge-Kutta coefficients.
bool alone
If true, this is a standalone solver.
bool linear = false
If true mass matrix is constant.
Detailed Description
template<class Solver>
class TimeIntegration::SIMExplicitRK< Solver >
Explicit Runge-Kutta based time stepping for SIM classes.
Template can be instanced over any SIM implementing ISolver, and which derive from SIMbase.
Constructor & Destructor Documentation
SIMExplicitRK()
template<class Solver > TimeIntegration::SIMExplicitRK< Solver >::SIMExplicitRK (Solver & solv, Method type, bool standalone = true) inline
Constructor.
Parameters
solv The simulator to do time stepping for
type The Runge-Kutta scheme to use
standalone If true, this is a standalone solver
References TimeIntegration::RKTableaux::A, TimeIntegration::RKTableaux::b, TimeIntegration::RKTableaux::c, TimeIntegration::EULER, TimeIntegration::HEUN, TimeIntegration::RKTableaux::order, utl::matrix< T >::resize(), TimeIntegration::SIMExplicitRK< Solver >::RK, TimeIntegration::RK3, and TimeIntegration::RK4.
Member Function Documentation
advanceStep()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::advanceStep (TimeStep & tp) inline
Advances the time step one step forward.
References TimeIntegration::SIMExplicitRK< Solver >::solver.
deSerialize()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::deSerialize (const std::map< std::string, std::string > & data) inline
Set internal state from a serialized state.
Parameters
[in] data Container for serialized data
References TimeIntegration::SIMExplicitRK< Solver >::solver.
getProcessAdm()
template<class Solver > const ProcessAdm& TimeIntegration::SIMExplicitRK< Solver >::getProcessAdm () const inline
Returns the parallel process administrator.
References TimeIntegration::SIMExplicitRK< Solver >::solver.
registerFields()
template<class Solver > void TimeIntegration::SIMExplicitRK< Solver >::registerFields (DataExporter & exporter) inline
Registers fields for output to a data exporter.
References TimeIntegration::SIMExplicitRK< Solver >::solver.
saveModel()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::saveModel (char * fileName, int & geoBlk, int & nBlock) inline
Opens a new VTF-file and writes the model geometry to it.
Parameters
[in] fileName File name used to construct the VTF-file name from
[out] geoBlk Running geometry block counter
[out] nBlock Running result block counter
References TimeIntegration::SIMExplicitRK< Solver >::solver.
saveStep()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::saveStep (const TimeStep & tp, int & nBlock) inline
Saves the converged results of a given time step to VTF file.
Parameters
[in] tp Time stepping parameters
[in] nBlock Running VTF block counter
References TimeIntegration::SIMExplicitRK< Solver >::solver.
serialize()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::serialize (std::map< std::string, std::string > & data) inline
Serialize internal state for restarting purposes.
Parameters
data Container for serialized data
References TimeIntegration::SIMExplicitRK< Solver >::solver.
solveRK()
template<class Solver > bool TimeIntegration::SIMExplicitRK< Solver >::solveRK (Vectors & stages, const TimeStep & tp) inline
Applies the Runge-Kutta scheme.
Parameters
stages Vector of stage vectors
[in] tp Time stepping information
References TimeIntegration::RKTableaux::A, utl::vector< T >::add(), TimeIntegration::SIMExplicitRK< Solver >::alone, TimeIntegration::RKTableaux::b, TimeIntegration::RKTableaux::c, TimeDomain::dt, TimeIntegration::SIMExplicitRK< Solver >::linear, utl::vector< T >::resize(), TimeIntegration::SIMExplicitRK< Solver >::RK, TimeIntegration::SIMExplicitRK< Solver >::solver, TimeStep::step, TimeDomain::t, and TimeStep::time.
Referenced by TimeIntegration::SIMExplicitRK< Solver >::solveStep(), and TimeIntegration::SIMExplicitRKE< Solver >::solveStep().
solveStep()
template<class Solver > virtual bool TimeIntegration::SIMExplicitRK< Solver >::solveStep (TimeStep & tp) inline virtual
Computes the solution for the current time step.
Reimplemented in TimeIntegration::SIMExplicitRKE< Solver >.
References TimeIntegration::SIMExplicitRK< Solver >::alone, TimeIntegration::SIMExplicitRK< Solver >::solver, TimeIntegration::SIMExplicitRK< Solver >::solveRK(), TimeStep::step, TimeDomain::t, and TimeStep::time.
The documentation for this class was generated from the following file:
Apps/Common/SIMExplicitRK.h