IFEM: SettingMap Class Reference
SettingMap Class Reference
A key-value store for settings.
#include <LinSolParams.h>
Public Member Functions
void addValue (const std::string &key, const std::string &value)
Add a value to the store.
std::string getStringValue (const std::string &key) const
Obtain a value as a string.
int getIntValue (const std::string &key) const
Obtain a value as an integer.
double getDoubleValue (const std::string &key) const
Obtain a value as an double.
bool hasValue (const std::string &key) const
Checks if the store holds a value for a key.
Protected Attributes
std::map< std::string, std::string > values
Map of key-value pairs.
Detailed Description
A key-value store for settings.
Member Function Documentation
addValue()
void SettingMap::addValue (const std::string & key, const std::string & value)
Add a value to the store.
Parameters
[in] key The key
[in] value The value
References values.
Referenced by LinSolParams::BlockParams::BlockParams(), LinSolParams::LinSolParams(), LinSolParams::BlockParams::read(), and LinSolParams::read().
getDoubleValue()
double SettingMap::getDoubleValue (const std::string & key) const
Obtain a value as an double.
Parameters
[in] key The key
References values.
Referenced by PETScSolParams::getDoubleValue(), PETScSchurPC::PETScSchurPC(), and setupWithPreType().
getIntValue()
int SettingMap::getIntValue (const std::string & key) const
Obtain a value as an integer.
Parameters
[in] key The key
References values.
Referenced by PETScSolParams::getIntValue(), ISTLMatrix::handleSolverReset(), PETScSchurPC::PETScSchurPC(), LinSolParams::BlockParams::read(), PETScSolParams::setupAdditiveSchwarz(), setupAMG(), setupAMG2_full(), PETScSolParams::setupPC(), ISTLSolParams::setupPCInternal(), PETScSolParams::setupSmoothers(), and setupWithPreType().
getStringValue()
std::string SettingMap::getStringValue (const std::string & key) const
Obtain a value as a string.
Parameters
[in] key The key
References values.
Referenced by condSetup(), PETScSolParams::getStringValue(), ISTLMatrix::handleSolverReset(), PETScSchurPC::PETScSchurPC(), LinSolParams::BlockParams::read(), PETScMatrix::setParameters(), setupAMG2(), setupAMG2_smoother(), PETScSolParams::setupCoarseSolver(), ISTLSolParams::setupPC(), PETScSolParams::setupPC(), ISTLSolParams::setupPCInternal(), PETScSolParams::setupSmoothers(), and setupWithPreType().
hasValue()
bool SettingMap::hasValue (const std::string & key) const
Checks if the store holds a value for a key.
Parameters
[in] key The key
References values.
Referenced by condSetup(), ISTLMatrix::handleSolverReset(), PETScSolParams::hasValue(), LinSolParams::BlockParams::read(), setupAMG(), setupAMG2_full(), and PETScSolParams::setupPC().
The documentation for this class was generated from the following files:
src/LinAlg/LinSolParams.h
src/LinAlg/LinSolParams.C