IFEM: Immersed::Geometry Class Reference
Immersed::Geometry Class Reference
Interface class representing a geometric object.
#include <ImmersedBoundaries.h>
Public Member Functions
virtual ~Geometry ()
Empty destructor.
virtual double Alpha (double X, double Y, double Z) const
Performs the inside-outside test for the geometric object.
virtual double Alpha (const Vec3 &X) const
Performs the inside-outside test for the geometric object.
virtual ElementBlock * tesselate () const
Creates a finite element model of the geometry for visualization.
Protected Member Functions
Geometry ()
The default constructor is protected to allow sub-classes only.
Detailed Description
Interface class representing a geometric object.
Member Function Documentation
Alpha()
virtual double Immersed::Geometry::Alpha (double X, double Y, double Z) const inline virtual
Performs the inside-outside test for the geometric object.
Alpha is used as an indicator here: Alpha = 0.0 if the point is lying outside the physical domain Alpha = 0.0 if the point is lying directly on the boundary Alpha = 1.0 if the point is lying inside the physical domain
Reimplemented in Hole2D, PerforatedPlate2D, and Oval2D.
Referenced by Alpha(), ASMs2DIB::filterResults(), ASMu2DIB::filterResults(), and Immersed::getQuadraturePoints().
The documentation for this class was generated from the following files:
src/ASM/ImmersedBoundaries.h
src/ASM/ImmersedBoundaries.C