IFEM: PiolaOperators::Residual Class Reference
PiolaOperators::Residual Class Reference
Common weak residual operators using div-compatible discretizations.
#include <PiolaOperators.h>
Static Public Member Functions
static void Convection (Vectors &EV, const FiniteElement &fe, const Vec3 &U, const Tensor &dUdX, const Vec3 &UC, const std::array< int, 3 > &idx, double scale, WeakOperators::ConvectionForm form=WeakOperators::CONVECTIVE)
Compute a convection term in a residual vector.
static void Gradient (Vectors &EV, const FiniteElement &fe, const std::array< int, 3 > &idx, double scale=1.0)
Compute a gradient term.
static void Laplacian (Vectors &EV, const FiniteElement &fe, const Tensor &dUdX, const std::array< int, 3 > &idx, double scale=1.0, bool stress=false)
Compute a laplacian term in a residual vector.
Detailed Description
Common weak residual operators using div-compatible discretizations.
Member Function Documentation
Convection()
void PiolaOperators::Residual::Convection (Vectors & EV, const FiniteElement & fe, const Vec3 & U, const Tensor & dUdX, const Vec3 & UC, const std::array< int, 3 > & idx, double scale, WeakOperators::ConvectionForm form = WeakOperators::CONVECTIVE) static
Compute a convection term in a residual vector.
Parameters
EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] U Advected field
[in] dUdX Advected field gradient
[in] UC Advecting field
idx Vector block indices
[in] scale Scaling factor for contribution
[in] form Which form of the convective form to use
References utl::matrix< T >::cols(), PiolaOperators::Copy(), FiniteElement::detJxW, utl::matrix< T >::fillColumn(), FiniteElement::grad(), utl::matrix< T >::multiply(), and FiniteElement::P.
Gradient()
void PiolaOperators::Residual::Gradient (Vectors & EV, const FiniteElement & fe, const std::array< int, 3 > & idx, double scale = 1.0) static
Compute a gradient term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
idx Vector block indices
[in] scale Scaling factor for contribution
References utl::matrix< T >::cols(), PiolaOperators::Copy(), FiniteElement::detJxW, FiniteElement::dNdX, and FiniteElement::dPdX.
Laplacian()
void PiolaOperators::Residual::Laplacian (Vectors & EV, const FiniteElement & fe, const Tensor & dUdX, const std::array< int, 3 > & idx, double scale = 1.0, bool stress = false) static
Compute a laplacian term in a residual vector.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] dUdX Current solution gradient
idx Vector block indices
[in] scale Scaling factor for contribution
[in] stress Whether to add extra stress formulation terms
References PiolaOperators::Copy(), FiniteElement::detJxW, FiniteElement::dPdX, and utl::matrix< T >::multiply().
The documentation for this class was generated from the following files:
Apps/Common/PiolaOperators.h
Apps/Common/PiolaOperators.C