IFEM: DomainDecomposition::OrientIterator Class Reference
DomainDecomposition::OrientIterator Class Reference
Iterator for matching nodes on edges/faces with a given orientation and index.
#include <DomainDecomposition.h>
Public Member Functions
OrientIterator (const ASMbase *pch, int orient, int lIdx, int basis, int dim=2)
Constructor.
OrientIterator (const ASMbase *pch, int orient, int lIdx)
Constructor for elements.
IntVec::const_iterator begin ()
Obtain start of node numbers.
IntVec::const_iterator end ()
Obtain end of node numbers.
size_t size () const
Obtain number of nodes.
Protected Attributes
IntVec nodes
Node number on boundary.
Detailed Description
Iterator for matching nodes on edges/faces with a given orientation and index.
Constructor & Destructor Documentation
OrientIterator() [1/2]
DomainDecomposition::OrientIterator::OrientIterator (const ASMbase * pch, int orient, int lIdx, int basis, int dim = 2)
Constructor.
Parameters
pch Slave patch
orient Orientation of boundary on slave
lIdx Index of boundary on slave
basis Basis to use for boundary on slave
dim Dimension to iterate over
References ASMbase::getBoundary1Nodes(), ASMbase::getBoundaryNodes(), ASMbase::getNoSpaceDim(), and ASMstruct::getSize().
OrientIterator() [2/2]
DomainDecomposition::OrientIterator::OrientIterator (const ASMbase * pch, int orient, int lIdx)
Constructor for elements.
Parameters
pch Slave patch
orient Orientation of boundary on slave
lIdx Index of boundary on slave
References ASMbase::getNoBoundaryElms(), ASMbase::getNoSpaceDim(), and ASMstruct::getNoStructElms().
The documentation for this class was generated from the following files:
src/ASM/DomainDecomposition.h
src/ASM/DomainDecomposition.C