IFEM: GlbNorm Class Reference
GlbNorm Class Reference
Class representing integrated global norms.
#include <GlbNorm.h>
Public Member Functions
GlbNorm (Vectors &v, ASM::FinalNormOp op=ASM::NONE)
The constructor initializes a reference to the global norm vector.
virtual ~GlbNorm ()
The destructor applies the operation myOp on myVals.
virtual bool assemble (const LocalIntegral *elmObj, int elmId=0)
Adds element norm quantities into the global norm object.
virtual bool threadSafe () const
Returns true if all elements can be assembled in parallel.
void delayAssembly ()
Flags that the element values are assembled in the final stage.
Public Member Functions inherited from GlobalIntegral
GlobalIntegral ()
The default constructor.
virtual ~GlobalIntegral ()
Empty destructor.
virtual void initialize (char)
Initializes the integrated quantity to zero.
virtual bool finalize (bool)
Finalizes the integrated quantity after element assembly.
virtual bool haveContributions (size_t, const std::vector< Property > &) const
Returns false if no contributions from a specified patch.
Private Member Functions
void applyFinalOp (double &value) const
Applies the operation myOp on the given value.
Private Attributes
Vectors & myVals
Reference to a vector of global norm values.
ASM::FinalNormOp myOp
Operation to be performed on summed values.
bool delAss
If true, element assembly is delayed.
Detailed Description
Class representing integrated global norms.
The class is essentially a vector of doubles, but is derived from GlobalIntegral such that it may be passed as argument to ASMbase::integrate.
Constructor & Destructor Documentation
GlbNorm()
GlbNorm::GlbNorm (Vectors & v, ASM::FinalNormOp op = ASM::NONE) explicit
The constructor initializes a reference to the global norm vector.
Parameters
[in] v Vector of global norm quantities
[in] op Operation to be performed after accumulating element norms
References delAss.
Member Function Documentation
assemble()
bool GlbNorm::assemble (const LocalIntegral * elmObj, int elmId = 0) virtual
Adds element norm quantities into the global norm object.
Parameters
[in] elmObj Pointer to the element norms to add into *this
[in] elmId Global number of the element associated with *elmObj
Reimplemented from GlobalIntegral.
References applyFinalOp(), delAss, ElmNorm::externalStorage(), myVals, and ElmNorm::size().
Referenced by SIMbase::solutionNorms().
The documentation for this class was generated from the following files:
src/ASM/GlbNorm.h
src/ASM/GlbNorm.C