IFEM: HDF5Reader Class Reference
HDF5Reader Class Reference
Read data from a HDF5 file.
#include <HDF5Reader.h>
Public Member Functions
HDF5Reader (const std::string &name, const ProcessAdm &adm)
The constructor opens a named HDF5-file.
bool readVector (const std::string &path, std::vector< int > &vec)
Reads an integer vector.
bool readVector (const std::string &path, std::vector< double > &vec)
Reads an double precision vector.
bool readDouble (const std::string &name, double &out)
Reads a single double value.
bool readString (const std::string &name, std::string &out)
Reads a text string.
bool read3DArray (const std::string &name, Matrix3D &data)
Reads a 3D array.
int getFieldSize (const std::string &fieldPath)
Returns number of patches for a field.
Public Member Functions inherited from HDF5Base
HDF5Base (const std::string &name, const ProcessAdm &adm)
The constructor opens a named HDF5-file.
virtual ~HDF5Base ()
The destructor closes the file.
Additional Inherited Members
Protected Member Functions inherited from HDF5Base
bool openFile (unsigned int flag)
Opens the HDF5 file.
void closeFile ()
Closes the HDF5 file.
Protected Attributes inherited from HDF5Base
std::string m_hdf5_name
The file name of the HDF5 file.
Detailed Description
Read data from a HDF5 file.
Constructor & Destructor Documentation
HDF5Reader()
HDF5Reader::HDF5Reader (const std::string & name, const ProcessAdm & adm)
The constructor opens a named HDF5-file.
Parameters
[in] name The name (without extension) of the data file
[in] adm The process administrator
Member Function Documentation
getFieldSize()
int HDF5Reader::getFieldSize (const std::string & fieldPath)
Returns number of patches for a field.
Parameters
[in] fieldPath Path to field in hdf5 file
References HDF5Base::openFile().
Referenced by FieldFuncHDF5::load(), and SIMinput::setInitialCondition().
read3DArray()
bool HDF5Reader::read3DArray (const std::string & name, Matrix3D & data)
Reads a 3D array.
Parameters
[in] name The name (path in HDF5 file) to the string
[out] data The 3D array to read data into
References HDF5Base::openFile(), and utl::matrix3d< T >::resize().
Referenced by TextureProperties::parse().
readDouble()
bool HDF5Reader::readDouble (const std::string & name, double & out)
Reads a single double value.
Parameters
[in] name The name (path in HDF5 file) to the string
[out] out The double to read data into
References HDF5Base::openFile().
Referenced by FieldFuncHDF5::findClosestLevel().
readString()
bool HDF5Reader::readString (const std::string & name, std::string & out)
Reads a text string.
Parameters
[in] name The name (path in HDF5 file) to the string
[out] out The string to read data into
References HDF5Base::openFile().
Referenced by FieldFuncHDF5::load(), and SIMinput::setInitialCondition().
readVector() [1/2]
bool HDF5Reader::readVector (const std::string & path, std::vector< double > & vec)
Reads an double precision vector.
Parameters
[in] path The path to the dataset to read
[out] vec The vector to read data into
References HDF5Base::openFile().
readVector() [2/2]
bool HDF5Reader::readVector (const std::string & path, std::vector< int > & vec)
Reads an integer vector.
Helper for reading data from HDF5 file.
Parameters
[in] path The path to the dataset to read
[out] vec The vector to read data into
References HDF5Base::openFile().
Referenced by FieldFuncHDF5::load(), and SIMinput::setInitialCondition().
The documentation for this class was generated from the following files:
src/Utility/FieldFunctions.C
src/Utility/HDF5Reader.h
src/Utility/HDF5Reader.C