IFEM: ASMs1DLag Class Reference
ASMs1DLag Class Reference
Driver for assembly of 1D Lagrange FE models.
#include <ASMs1DLag.h>
Public Member Functions
ASMs1DLag (unsigned char n_s=1, unsigned char n_f=1)
Default constructor.
ASMs1DLag (const ASMs1DLag &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMs1DLag (const ASMs1DLag &patch)
Default copy constructor copying everything.
virtual ~ASMs1DLag ()
Empty destructor.
virtual bool write (std::ostream &os, int=0) const
Writes the FEM basis to given stream.
virtual bool generateOrientedFEModel (const Vec3 &Zaxis)
Generates a beam finite element model for the patch.
virtual void clear (bool retainGeometry=false)
Clears the contents of the patch, making it empty.
virtual bool getElementCoordinates (Matrix &X, int iel, bool=true) const
Returns a matrix with nodal coordinates for an element.
virtual void getNodalCoordinates (Matrix &X, bool=false) const
Returns a matrix with all nodal coordinates within the patch.
virtual Vec3 getCoord (size_t inod) const
Returns the global coordinates for the given node.
virtual Vec3 getElementCenter (int iel) const
Returns the geometric center of an element.
virtual bool updateCoords (const Vector &displ)
Updates the nodal coordinates for this patch.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates an integral over the interior patch domain.
virtual bool integrate (Integrand &integrand, int lIndex, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch end.
virtual int evalPoint (const double *xi, double *param, Vec3 &X) const
Evaluates the geometry at a specified point.
virtual bool tesselate (ElementBlock &grid, const int *) const
Creates a line element model of this patch for visualization.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *, int, bool) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *, bool, int, int) const
Evaluates the primary solution field at the nodal points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *, char) const
Evaluates the secondary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *, bool regular) const
Evaluates the secondary solution field at the nodes/elements.
virtual int getSize (int=0) const
Returns the number of nodal points in the patch.
virtual IntMat getElmNodes (int) const
Returns the matrix of nodal point correspondance.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int, bool) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool=true, int deriv=0, int=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual Go::GeomObject * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool=true) const
Evaluates the secondary solution field at the given points.
virtual int getSize (int=0) const
Returns the number of nodal points in the patch.
virtual bool getSize (int &n1, int &n2, int &n3, int basis) const
Returns the number of nodal points in each parameter direction.
Public Member Functions inherited from ASMs1D
ASMs1D (unsigned char n_s=1, unsigned char n_f=1)
Default constructor.
ASMs1D (const ASMs1D &patch, unsigned char n_f=0)
Copy constructor.
virtual ~ASMs1D ()
Empty destructor.
Go::SplineCurve * getCurve () const
Returns the spline curve representing the geometry of this patch.
virtual bool read (std::istream &)
Creates an instance by reading the given input stream.
virtual bool generateFEMTopology ()
Generates the finite element topology data for the patch.
void applyTwist (const RealFunc &twist)
Applies a twist angle to the beam transformation matrices.
const Tensor & getRotation (size_t inod) const
Returns the current rotation tensor for the given node.
bool updateRotations (const Vector &displ, bool reInit=false)
Updates the nodal rotations for this patch.
void updateRotations ()
Updates the previous nodal rotations for this patch at convergence.
virtual void getBoundaryNodes (int lIndex, IntVec &nodes, int, int thick, int, bool local) const
Finds the global (or patch-local) node number on a patch end.
virtual int getNodeSetIdx (const std::string &setName) const
Returns (1-based) index of a predefined node set in the patch.
virtual const IntVec & getNodeSet (int iset) const
Returns an indexed pre-defined node set.
virtual bool isInNodeSet (int iset, int inod) const
Checks if node inod is within predefined node set iset.
virtual int parseNodeSet (const std::string &setName, const char *cset)
Defines a node set by parsing a list of node numbers.
virtual std::pair< size_t, double > findClosestNode (const Vec3 &X) const
Finds the node that is closest to the given point.
std::pair< int, double > findElement (const Vec3 &X) const
Finds the element that contains the given point.
virtual bool refine (const LR::RefineData &prm, Vectors &)
Refines the mesh adaptively.
virtual bool refine (const RealArray &xi)
Refines the parametrization by inserting extra knots.
virtual bool uniformRefine (int nInsert)
Refines the parametrization by inserting extra knots uniformly.
virtual bool raiseOrder (int ru)
Raises the order of the SplineCurve object for this patch.
virtual bool createProjectionBasis (bool init)
Creates a separate projection basis for this patch.
virtual int constrainNode (double xi, int dof, int code)
Constrains a node identified by a relative parameter value.
virtual size_t constrainEndLocal (int dir, int dof, int code)
Constrains all DOFs in local directions at a given end point.
virtual bool connectPatch (int vertex, ASM1D &neighbor, int nvertex, int thick=1)
Connects matching nodes on two adjacent vertices.
virtual void closeBoundaries (int, int basis, int master)
Makes the two end vertices of the curve periodic.
virtual int findElementContaining (const double *param) const
Returns the element that contains a specified spatial point.
virtual double findPoint (Vec3 &X, double *param) const
Searches for the specified Cartesian point in the patch.
virtual bool getSolution (Matrix &sField, const Vector &locSol, const IntVec &nodes) const
Extract the primary solution field at the specified nodes.
virtual bool evalProjSolution (Matrix &sField, const Vector &locSol, const int *npe, int) const
Evaluates the projected solution field at all visualization points.
virtual bool evaluate (const FunctionBase *func, RealArray &vec, int, double time) const
Evaluates and interpolates a function over a given geometry.
Go::SplineCurve * projectSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual Go::GeomObject * evalSolution (const IntegrandBase &integrand) const
Projects the secondary solution field onto the primary basis.
virtual Fields * getProjectedFields (const Vector &coefs, size_t=0) const
Returns a field using the projection basis.
virtual bool getGridParameters (RealArray &prm, int nSegSpan) const
Calculates parameter values for visualization nodal points.
virtual void evaluateBasis (double u, double, double, Vector &N) const
Evaluates the basis functions at the specified point.
void extractBasis (double u, Vector &N) const
Establishes the vector with basis function values.
void extractBasis (double u, Vector &N, Matrix &dNdu) const
Establishes matrices with basis functions and 1st derivatives.
void extractBasis (double u, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2) const
Establishes matrices with basis functions, 1st and 2nd derivatives.
void extractBasis (double u, Vector &N, Matrix &dNdu, Matrix3D &d2Ndu2, Matrix4D &d3Ndu3) const
Establishes matrices with basis functions, 1st, 2nd and 3rd derivatives.
virtual bool getOrder (int &p1, int &p2, int &p3) const
Returns the polynomial order in each parameter direction.
virtual bool getSize (int &n1, int &n2, int &n3, int basis) const
Returns the number of nodal points in each parameter direction.
virtual bool getNoStructElms (int &n1, int &n2, int &n3) const
Returns the number of elements in each parameter direction.
virtual size_t getNoNodes (int basis=0) const
Returns the total number of nodes in this patch.
virtual size_t getNoProjectionNodes () const
Returns the number of projection nodes for this patch.
virtual bool getParameterDomain (Real2DMat &u, IntVec *corners) const
Returns parameter values and node numbers of the domain corners.
virtual void getElmConnectivities (IntMat &neigh, int basis=ASM::INTEGRATION_BASIS) const
Calculates the matrix of element neighbour connectivities.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *f, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a scalar field over a given geometry.
virtual bool evaluate (const FunctionBase *f, RealArray &vec, int basisNum=1, double time=0.0) const
Evaluates and interpolates a scalar function over a given geometry.
Public Member Functions inherited from ASMstruct
virtual ~ASMstruct ()
The destructor frees the dynamically allocated spline objects.
virtual bool empty () const
Checks if the patch is empty.
virtual bool diracPoint (Integrand &integr, GlobalIntegral &glInt, const double *u, const Vec3 &pval)
Integrates a spatial dirac-delta function over a patch.
virtual bool separateProjectionBasis () const
Checks if a separate projection basis is used for this patch.
virtual void swapProjectionBasis ()
Swaps between the first and second projection basis.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const int *npe, int n_f=0, bool piola=false) const
Evaluates the primary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular=true, int deriv=0, int n_f=0) const
Evaluates the primary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const int *npe=nullptr, char project=0) const
Evaluates the secondary solution field at all visualization points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const RealArray *gpar, bool regular=true) const
Evaluates the secondary solution field at the given points.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
Public Member Functions inherited from ASMbase
virtual ~ASMbase ()
The destructor frees the dynamically allocated data objects.
ASMbase * cloneUnShared () const
Returns a copy of this patch with identical FE discretization.
virtual bool readBasis (std::istream &, size_t)
Reads a basis from the given input stream.
virtual void addHole (double, double, double)
Adds a circular immersed boundary in the physical geometry.
virtual void addHole (double, double, double, double, double)
Adds an oval immersed boundary in the physical geometry.
virtual bool setGeometry (RealFunc *, double, double)
Defines the immersed geometry from a scalar function.
virtual bool addXElms (short int dim, short int item, size_t nXn, IntVec &nodes)
Adds extraordinary elements associated with a patch boundary.
bool addLagrangeMultipliers (size_t iel, const IntVec &mGLag, unsigned char nnLag=1)
Adds a set of Lagrange multipliers to the specified element.
bool addGlobalLagrangeMultipliers (const IntVec &mGLag, unsigned char nnLag=1)
Adds global Lagrange multipliers to the system.
virtual void setGauss (int ng)
Defines the numerical integration scheme nGauss in the patch.
void setNoFields (unsigned char n)
Defines the number of solution fields in the patch.
void setElementActivator (IntFunc *efunc)
Sets the element activation function.
const IntFunc * getElementActivator () const
Returns a pointer to the element activation function.
virtual void setMinimumSize (double)
Sets the minimum element size for adaptive refinement.
virtual double getMinimumSize (int=0) const
Defines the minimum element size for adaptive refinement.
virtual bool checkElementSize (int, bool=true) const
Checks if the specified element is larger than the minimum size.
unsigned char getNoSpaceDim () const
Returns the number of spatial dimensions.
unsigned char getNoParamDim () const
Returns the number of parameter dimensions.
virtual unsigned char getNoFields (int b=0) const
Returns the number of solution fields.
unsigned char getNoLagPerNode () const
Returns the number of Lagrange multipliers per node.
virtual size_t getNodeIndex (int globalNum, bool=false) const
Returns local 1-based index of the node with given global number.
virtual int getNodeID (size_t inod, bool=false) const
Returns the global node number for the given node.
size_t getElmIndex (int globalNum) const
Returns local 1-based index of element with given global number.
int getElmID (size_t iel) const
Returns the global element number for the given element.
virtual unsigned char getNodalDOFs (size_t inod) const
Returns the number of DOFs per node.
virtual char getNodeType (size_t inod) const
Returns the classification of a node.
bool isLMn (size_t n) const
Returns true if node n is a Lagrange multiplier node.
bool isRMn (size_t n) const
Returns true if node n is a master node of a rigid coupling.
char getLMType (size_t inod) const
Returns the type of a Lagrange multiplier node.
virtual void getBoundary1Nodes (int lIndex, IntVec &nodes, int basis=0, int orient=-1, bool local=false, bool open=false) const
Finds the global (or patch-local) node numbers on a patch boundary.
void getBoundaryElms (int lIndex, IntVec &elms, int orient=-1, bool local=false) const
Finds the global (or patch-local) element numbers on a boundary.
virtual int parseNodeBox (const std::string &, const char *)
Defines a node set by parsing a 3D bounding box.
virtual int getElementSetIdx (const std::string &) const
Returns (1-based) index of a predefined element set in the patch.
virtual const IntVec & getElementSet (int) const
Returns an indexed predefined element set.
virtual bool getElementSet (int, std::string &) const
Returns the name of an indexed predefined element set.
virtual bool isInElementSet (int, int) const
Checks if an element is within a predefined element set.
virtual int parseElemSet (const std::string &, const char *)
Defines an element set by parsing a list of element numbers.
virtual int parseElemBox (const std::string &, const std::string &, const char *)
Defines an element set by parsing a 3D bounding box.
void printNodes (std::ostream &os) const
Prints out the nodal coordinates of this patch to the given stream.
void printElements (std::ostream &os) const
Prints out element connections of this patch to the given stream.
virtual void printElmInfo (int, const IntegrandBase *) const
Prints out additional app-dependent element information.
virtual void shiftGlobalNodeNums (int nshift)
Increase all global node numbers by nshift.
void setGlobalNodeNums (const IntVec &nodes)
Sets the global node numbers for this patch.
const IntVec & getMyNodeNums () const
Returns the actual global node numbers of this patch.
const IntVec & getGlobalNodeNums () const
Returns the global node numbers of this patch.
virtual void shiftGlobalElmNums (int eshift)
Increase all global element numbers by eshift.
const IntVec & getGlobalElementNums () const
Returns the global element numbers of this patch.
void setActiveElements (IntVec *active)
Sets the list of active elements during assembly.
bool isElementActive (int iel, double time=-1.0) const
Returns true if element with 0-based index iel is active.
bool inActive (double time) const
Returns true if none of the elements in the patch are active.
double getAge (int iel, double time) const
Returns the age of the element with 0-based index iel.
bool isElementInPartition (int iel) const
Returns true if element is in process partition.
const IntVec & getElementNodes (int iel) const
Returns the nodal point correspondance array for an element.
virtual size_t getNoBasis () const
Returns number of bases of this patch.
size_t getNoElms (bool includeZeroVolElms=false, bool includeXElms=false) const
Returns the total number of elements in this patch.
int getMaxElmNo () const
Returns the highest external element number in this patch.
virtual size_t getNoBoundaryElms (char, char) const
Returns the number of elements on a boundary.
size_t getNoMPCs () const
Returns the total number of multi-point constraint equations.
virtual void getNoIntPoints (size_t &nPt, size_t &nIPt)
Computes the total number of integration points in this patch.
virtual void getNoBouPoints (size_t &nPt, char ldim, char lindx)
Computes the number of boundary integration points in this patch.
BCVec::const_iterator begin_BC () const
Returns the beginning of the BCode array.
BCVec::const_iterator end_BC () const
Returns the end of the BCode array.
IntMat::const_iterator begin_elm () const
Returns the beginning of the MNPC array.
IntMat::const_iterator end_elm () const
Returns the end of the MNPC array.
MPCIter begin_MPC () const
Returns the beginning of the mpcs set.
MPCIter end_MPC () const
Returns the end of the mpcs set.
MPC * findMPC (int node, int dof) const
Returns a pointer to the MPC object for a specified slave, if any.
bool isShared () const
Returns true if this patch shares FE data with another patch.
bool hasXNodes () const
Returns true if this patch has additional (extraordinary) nodes.
virtual void copyParameterDomain (const ASMbase *)
Copies the parameter domain from another patch.
bool mergeNodes (size_t inod, int globalNum, bool verbose=true)
Merges a given node in this patch with a given global node.
int renumberNodes (std::map< int, int > &old2new, int &nNod)
Renumbers the global node numbers in this patch.
bool renumberNodes (const std::map< int, int > &old2new, const std::vector< int > &new2old={}, int renumGN=0, std::map< int, int > *degenElm=nullptr)
Renumbers the global node numbers referred by this patch.
virtual bool initConstraints ()
Initializes the multi-point constraint coefficients.
virtual void setNodeNumbers (const IntVec &nodes)
Sets the global node numbers for this patch.
bool hasTimeDependentDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc)
Checks for time-dependent in-homogeneous Dirichlet conditions.
virtual bool updateDirichlet (const std::map< int, RealFunc * > &func, const std::map< int, VecFunc * > &vfunc, double time=0.0, const std::map< int, int > *g2l=nullptr)
Updates the time-dependent in-homogeneous Dirichlet coefficients.
virtual bool transform (const Matrix &)
Applies a transformation matrix from local to global system.
virtual void initMADOF (const int *)
Initializes the patch level MADOF array for mixed problems.
virtual void generateThreadGroups (const Integrand &, bool, bool)
Generates element groups for multi-threading of interior integrals.
virtual void generateThreadGroups (char, bool, bool)
Generates element groups for multi-threading of boundary integrals.
virtual void generateThreadGroupsFromElms (const IntVec &)
Generates element groups for multi-threading based on a partition.
virtual void generateProjThreadGroupsFromElms (const IntVec &)
Generates element groups for multi-threading based on a partition.
virtual bool validateThreadGroups (const SAM *) const
Validates the threading groups based on the assembly data in SAM.
virtual void changeNumThreads ()
Hook for changing number of threads.
virtual bool integrateEdge (Integrand &integrand, int lEdge, GlobalIntegral &glbInt, const TimeDomain &time)
Evaluates a boundary integral over a patch edge.
virtual bool integrate (Integrand &integrand, GlobalIntegral &glbInt, const TimeDomain &time, const ASM::InterfaceChecker &iChk)
Evaluates an integral over element interfaces in the patch.
virtual ElementBlock * immersedGeometry (char *) const
Returns an additional geometry to visualize (immersed boundaries).
virtual ElementBlock * extraGeometry (char *) const
Returns an additional geometry to visualize (spiders, etc.).
virtual void filterResults (Matrix &, const ElementBlock *) const
Filters out result point values that are outside physical domain.
virtual bool immersedSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the immersed geometry points.
virtual bool extraSolution (Matrix &, const Vector &) const
Evaluates the primary solution at the extra geometry points.
virtual bool evalSolutionPiola (Matrix &sField, const Vector &locSol, const RealArray *gpar, bool regular) const
Evaluates the primary solution field with Piola mapping.
virtual bool evaluate (const ASMbase *basis, const Vector &locVec, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a field over a given geometry.
virtual bool evaluate (const Field *f, RealArray &vec, int basisNum=1) const
Evaluates and interpolates a scalar field over a given geometry.
virtual bool evalSolution (Matrix &sField, const IntegrandBase &integrand, const IntVec &elements) const
Evaluates the secondary solution field at element centers.
bool globalL2projection (Matrix &sField, const L2Integrand &integrand, bool continuous=false, bool enforceEnds=false) const
Projects the secondary solution using a (discrete) global L2-fit.
bool L2projection (Matrix &sField, IntegrandBase *integrand, const TimeDomain &time)
Projects the secondary solution using a continuous global L2-fit.
bool L2projection (Matrix &fVals, FunctionBase *function, double t=0.0)
Projects an explicit function using a continuous global L2-fit.
bool L2projection (const std::vector< Matrix * > &fVals, const std::vector< FunctionBase * > &function, double t=0.0)
Projects explicit functions using a continuous global L2-fit.
virtual size_t getNoRefineNodes () const
Returns the number of nodes on refinement basis for this patch.
virtual size_t getNoRefineElms () const
Returns the number of elements on refinement basis for this patch.
virtual Field * getProjectedField (const Vector &) const
Returns a field using the projection basis.
virtual void extractElmRes (const Vector &globRes, Vector &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
virtual void extractElmRes (const Matrix &globRes, Matrix &elmRes, size_t internalFirst=0) const
Extracts element results for this patch from a global vector.
bool extractNodalVec (const RealArray &globVec, RealArray &nodeVec, const int *madof, int ngnod=-1) const
Extracts nodal results for this patch from the global vector.
virtual void extractNodeVec (const RealArray &globVec, RealArray &nodeVec, unsigned char nndof=0, int basis=0) const
Extracts nodal results for this patch from the global vector.
virtual bool injectNodeVec (const RealArray &nodeVec, RealArray &globVec, unsigned char nndof=0, int basis=0) const
Injects nodal results for this patch into the global vector.
bool injectNodalVec (const RealArray &nodeVec, RealArray &globVec, const IntVec &madof, int basis=0) const
Injects nodal results for this patch into the global vector.
bool add2PC (int slave, int dir, int master, int code=0)
Creates and adds a two-point constraint to this patch.
bool addMPC (MPC *&mpc, int code=0, bool verbose=false, bool overrideD=false)
Adds a general multi-point-constraint (MPC) equation to this patch.
virtual bool addRigidCpl (int lindx, int ldim, int basis, int &gMaster, const Vec3 &Xmaster, bool extraPt=true)
Adds MPC-equations representing a rigid coupling to this patch.
void addRigidCouplings (int gMaster, const Vec3 &Xmaster, const IntVec &slaveNodes)
Adds MPC-equations representing a rigid coupling to this patch.
void constrainPatch (int dof, int code=0)
Constrains all nodes in the patch.
void constrainNodes (const IntVec &nodes, int dof, int code=0, bool overrideD=false)
Constrains a list of nodes in the patch.
bool constrainXnode (int node, int dof, int code=0)
Constrains an extraordinary node in the patch.
int prescribe (size_t inod, int dirs, int code, bool overrideD=false)
Constrains DOFs in the given node to the given value.
int fix (size_t inod, int dirs=123)
Constrains DOFs in the given node to zero.
bool isFixed (int node, int dof, bool all=false) const
Checks if the given DOFs are fixed.
Public Member Functions inherited from ASMunstruct
virtual ~ASMunstruct ()
Empty destructor.
virtual void remapErrors (RealArray &errors, const RealArray &orig, bool=false) const
Remaps element-wise errors from geometry mesh to refinement mesh.
virtual IntVec getBoundaryCovered (const IntSet &) const
Returns all boundary functions that are covered by the given nodes.
virtual void extendRefinementDomain (IntSet &, const IntSet &) const
Extends the refinement domain with information for neighbors.
virtual void storeMesh (const std::string &fName, int fType=15) const
Stores the mesh basis to encapsulated postscript files.
Public Member Functions inherited from ASM1D
virtual ~ASM1D ()
Empty destructor.
ASMbase * clone (unsigned char *nf=nullptr) const
Returns a copy of this patch with identical FE discretization.
virtual bool refine (const std::vector< double > &xi)=0
Refines the parametrization by inserting extra knots.
virtual bool getGridParameters (std::vector< double > &prm, int nSegSpan) const =0
Calculates parameter values for visualization nodal points.
Protected Attributes
size_t nx
Number of nodes.
int p1
Polynomial order of the basis.
Protected Attributes inherited from ASMs1D
std::shared_ptr< Go::SplineCurve > curv
The actual spline curve object.
std::shared_ptr< Go::SplineCurve > proj
Spline curve for projection basis.
std::map< size_t, size_t > xnMap
Node index map used by getCoord()
std::map< size_t, size_t > nxMap
Node index map used by getNodeID()
IntMat projMNPC
Matrix of Nodal Point Correspondance for projection.
IntVec projMLGE
Matrix of Local to Global Element numbers for projection.
const TensorVec & elmCS
Element coordinate systems (for 3D beams)
const TensorVec & nodalT
Nodal rotation tensors (for 3D beams)
TensorVec myCS
The actual element coordinate systems.
TensorVec myT
The actual nodal rotation tensors.
TensorVec prevT
Nodal rotation tensors of last converged configuration.
std::vector< ASM::NodeSet > nodeSets
Node sets for Dirichlet BCs.
Protected Attributes inherited from ASMstruct
std::shared_ptr< Go::GeomObject > geomB
Pointer to spline object of the geometry basis.
std::shared_ptr< Go::GeomObject > projB
Pointer to spline object of the projection basis.
std::shared_ptr< Go::GeomObject > projB2
Pointer to spline object of the secondary projection basis.
ThreadGroups projThreadGroups
Element groups for multi-threaded assembly - projection basis.
ThreadGroups proj2ThreadGroups
Element groups for multi-threaded assembly - second projection basis.
Protected Attributes inherited from ASMbase
unsigned char ndim
Number of parametric dimensions (1, 2 or 3)
unsigned char nsd
Number of space dimensions (ndim <= nsd <= 3)
unsigned char nf
Number of primary solution fields (1 or larger)
unsigned char nLag
Number of Lagrange multipliers per node.
size_t nel
Number of regular elements in this patch.
size_t nnod
Number of regular nodes in this patch.
const IntVec & MLGE
Matrix of Local to Global Element numbers.
const IntVec & MLGN
Matrix of Local to Global Node numbers.
const IntMat & MNPC
Matrix of Nodal Point Correspondance.
const char shareFE
Flag telling whether this patch shares its data with another patch.
BCVec BCode
Array of Boundary Condition codes.
MPCMap dCode
Inhomogeneous Dirichlet condition codes for the MPCs.
MPCSet mpcs
All multi-point constraints with the slave in this patch.
IntVec myMLGE
The actual Matrix of Local to Global Element numbers.
IntVec myMLGN
The actual Matrix of Local to Global Node numbers.
IntMat myMNPC
The actual Matrix of Nodal Point Correspondance.
IntVec myElms
Elements on patch - used with partitioning.
int nGauss
Numerical integration scheme for this patch.
size_t firstEl
Global index to first element within this patch.
size_t firstIp
Global index to first interior integration point.
std::map< char, size_t > firstBp
Global indices to first integration point for the Neumann boundaries.
ASMVec neighbors
Patches having nodes in common with this one.
std::map< size_t, XYZ > myRmaster
Rigid master nodal points.
Protected Attributes inherited from ASMLagBase
const Vec3Vec & coord
Const reference to the nodal coordinate container.
Vec3Vec myCoord
Nodal coordinate container.
Static Private Member Functions
static void createMNPC (size_t nel, int p1, IntMat &MNPC)
Creates matrix of nodal point correspondance for a structured grid.
Additional Inherited Members
Public Types inherited from ASMbase
using BCVec = std::vector< BC >
Nodal boundary condition container.
Static Public Member Functions inherited from ASMs1D
static void scatterInd (int p1, int start, IntVec &index)
Auxilliary function for computation of basis function indices.
Static Public Member Functions inherited from ASMbase
static void resetNumbering (int n=0)
Resets the global element and node counters.
static int renumberNodes (const ASMVec &model, std::map< int, int > &old2new)
Renumbers all global node numbers in the entire model.
static void mergeAndGetAllMPCs (const ASMVec &model, MPCSet &allMPCs)
Computes the set of all MPC-equations over the whole model.
static void resolveMPCchains (const MPCSet &allMPCs, const ASMVec &model, bool setPtrOnly=false)
Resolves (possibly multi-level) chaining in MPC-equations.
Static Public Member Functions inherited from ASM1D
static ASMbase * create (ASM::Discretization type, unsigned char nd, unsigned char nf)
Creates a one-parametric patch of specified discretization type.
static ASMbase * create (ASM::Discretization type, unsigned char nf=1)
Creates a one-parametric patch of specified discretization type.
static double getElementSize (const std::vector< Vec3 > &XC)
Returns characteristic element size based on end point coordinates.
Public Attributes inherited from ASMbase
size_t idx
Index of this patch in the multi-patch model.
Static Public Attributes inherited from ASMbase
static bool fixHomogeneousDirichlet = true
If true, pre-eliminate fixed DOFs.
static int dbgElm = 0
One-based element index to print debugging info for.
static double modelSize = 1.0
Characteristic model size.
Protected Types inherited from ASMbase
using XYZ = std::array< double, 3 >
Convenience type definition.
Protected Member Functions inherited from ASMs1D
virtual void findBoundaryElms (IntVec &elms, int lIndex, int=0) const
Finds the path-local element numbers on a patch boundary.
virtual bool assembleL2matrices (SystemMatrix &A, SystemVector &B, const L2Integrand &integrand, bool continuous) const
Assembles L2-projection matrices for the secondary solution.
virtual bool initLocalElementAxes (const Vec3 &Zaxis)
Initializes the local element axes for a patch of beam elements.
bool connectBasis (ASMs1D &neighbor, int slave, int master, int thick=1)
Connects matching nodes on two adjacent vertices.
bool getGrevilleParameters (RealArray &prm) const
Calculates parameter values for the Greville points.
double getKnotSpan (int i) const
Returns the parametric length on the i'th knot-span.
virtual void getElementBorders (int iel, double *u) const
Computes the element border parameters.
double getElementEnds (int i, std::vector< Vec3 > &XC) const
Computes the element end coordinates.
bool getElementNodalRotations (TensorVec &T, size_t iel) const
Returns nodal rotation matrices for an element, if any.
Tensor getLocal2Global (double u) const
Returns the local-to-global transformation at a parametric point.
Protected Member Functions inherited from ASMstruct
ASMstruct (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMstruct (const ASMstruct &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
bool addXNodes (unsigned short int dim, size_t nXn, IntVec &nodes)
Adds extraordinary nodes associated with a patch boundary.
bool checkThreadGroups (const std::vector< std::set< int >> &nodes, int group, bool ignoreGlobalLM)
Performs a sanity check on the thread groups.
Protected Member Functions inherited from ASMbase
ASMbase (unsigned char n_p, unsigned char n_s, unsigned char n_f)
The constructor sets the number of space dimensions and fields.
ASMbase (const ASMbase &patch, unsigned char n_f)
Special copy constructor for sharing of FE data.
ASMbase (const ASMbase &patch)
Default copy constructor, copying everything except neighbors.
void addLocal2GlobalCpl (int iSlave, int master, const Tensor &Tlg)
Creates constraint equations coupling global DOFs to local DOFs.
bool add3PC (int slave, int dir, int master1, int master2, int code=0)
Creates and adds a three-point constraint to this patch.
bool addPeriodicity (size_t master, size_t slave, int dir)
Creates and adds a periodicity constraint to this patch.
void makePeriodic (size_t master, size_t slave, int dirs=123)
Creates periodicity constraints between two nodes in this patch.
void addNeighbor (ASMbase *pch)
Adds a patch to the list of neighbors of this patch.
bool createRgdMasterNode (int &gMaster, const Vec3 &Xmaster)
Creates an additional master node for a rigid coupling.
void addRigidMPC (int gSlave, int gMaster, const Vec3 &dX)
Adds MPC-equations representing a rigid arm to a 6-DOF node.
int getNoGaussPt (int p, bool neumann=false) const
Returns the number of Gauss points to use in one direction.
int searchCtrlPt (RealArray::const_iterator cit, RealArray::const_iterator end, const Vec3 &X, int dimension, double tol=0.001) const
Helper method used by evalPoint to search for a control point.
bool allDofs (int dirs) const
Returns true if dirs constains all local DOFs in the patch.
bool writeLagBasis (std::ostream &os, const char *type) const
Writes a Lagrangian basis to the given stream.
Protected Member Functions inherited from ASMunstruct
ASMunstruct ()
The constructor is protected to allow objects of sub-classes only.
Protected Member Functions inherited from ASM1D
ASM1D ()
The constructor is protected to allow objects of sub-classes only.
Protected Member Functions inherited from ASMLagBase
ASMLagBase ()
Default constructor.
ASMLagBase (const ASMLagBase &patch, bool cpCoord=true)
Copy constructor.
virtual ~ASMLagBase ()
Empty destructor.
bool nodalField (Matrix &field, const Vector &sol, size_t nno) const
Direct nodal evaluation of a solution field.
Vec3 getGeometricCenter (const std::vector< int > &MNPC) const
Returns the geometric center of an element.
bool updateCoords (const Vector &displ, unsigned char nsd)
Updates the nodal coordinates for this patch.
void updateOrigin (const Vec3 &origin)
Updates patch origin by adding a constant to all nodes.
Static Protected Member Functions inherited from ASMbase
static bool deformedConfig (const Matrix &Xnod, Vectors &eVec, bool force2nd=false)
Calculates the deformed configuration for current element.
static bool collapseNodes (ASMbase &pch1, int node1, ASMbase &pch2, int node2)
Collapses the given two nodes into one.
Static Protected Attributes inherited from ASMbase
static std::map< int, int > xNode
Auxilliary node number map used when establishing Dirichlet constraints.
static int gEl = 0
Global element counter.
static int gNod = 0
Global node counter.
Detailed Description
Driver for assembly of 1D Lagrange FE models.
This class contains methods for 1D Lagrange patches.
Member Function Documentation
clear()
void ASMs1DLag::clear (bool retainGeometry = false) virtual
Clears the contents of the patch, making it empty.
Parameters
[in] retainGeometry If true, the spline geometry is not cleared. This is used to reinitialize the patch after it has been refined.
Reimplemented from ASMs1D.
References ASMs1D::clear(), ASMLagBase::myCoord, nx, and p1.
evalPoint()
int ASMs1DLag::evalPoint (const double * xi, double * param, Vec3 & X) const virtual
Evaluates the geometry at a specified point.
Parameters
[in] xi Dimensionless parameters in range [0.0,1.0] of the point
[out] param The parameters of the point in the knot-span domain
[out] X The Cartesian coordinates of the point
Returns
Local node number within the patch that is closest to the point
Reimplemented from ASMs1D.
References ASMLagBase::coord, ASMs1D::curv, utl::find_closest(), ASMs1D::getGridParameters(), and p1.
evalSolution() [1/9]
Go::GeomObject * ASMs1D::evalSolution
Projects the secondary solution field onto the primary basis.
Parameters
[in] integrand Object with problem-specific data and methods
References ASMbase::MLGN, and ASMbase::nnod.
evalSolution() [2/9]
bool ASMs1DLag::evalSolution (Matrix & sField, const IntegrandBase & integrand, const int * , char) const virtual
Evaluates the secondary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
The number of visualization points is the same as the order of the Lagrange elements by default.
Reimplemented from ASMs1D.
References evalSolution().
evalSolution() [3/9]
bool ASMs1D::evalSolution
Evaluates the secondary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] npe Number of visualization nodes over each knot span
[in] project Flag indicating the projection method
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch. If npe is null, the solution is evaluated at the Greville points and then projected onto the spline basis to obtain the control point values, which then are returned through sField. If npe is not null and project is defined, the solution is also projected onto the spline basis, and then evaluated at the npe points.
References ASMbase::MLGN, and ASMbase::nnod.
evalSolution() [4/9]
bool ASMs1DLag::evalSolution (Matrix & sField, const IntegrandBase & integrand, const RealArray * , bool regular) const virtual
Evaluates the secondary solution field at the nodes/elements.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] regular If true, evaluate at all element centers. Otherwise, evaluate at all nodal points.
Reimplemented from ASMs1D.
Reimplemented in ASMs1DSpec.
References FiniteElement::age, Vec4::assign(), Lagrange::computeBasis(), FiniteElement::detJxW, FiniteElement::dNdX, utl::matrixBase< T >::empty(), IntegrandBase::evalSol(), utl::matrix< T >::fillColumn(), ASMbase::firstEl, getElementCoordinates(), Integrand::getIntegrandType(), IntegrandBase::getTimeLevel(), ItgPoint::idx, ItgPoint::iel, utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, FiniteElement::N, ASMbase::nel, ASMbase::nnod, Integrand::NO_DERIVATIVES, p1, utl::matrix< T >::resize(), utl::vector< T >::size(), Vec4::t, ItgPoint::xi, and FiniteElement::Xn.
evalSolution() [5/9]
bool ASMs1D::evalSolution
Evaluates the secondary solution field at the given points.
Parameters
[out] sField Solution field
[in] integrand Object with problem-specific data and methods
[in] gpar Parameter values of the result sampling points
The secondary solution is derived from the primary solution, which is assumed to be stored within the integrand for current patch.
References ASMs1D::myCS, ASMs1D::myT, ASMbase::nel, and ASMbase::nnod.
evalSolution() [6/9]
bool ASMs1DLag::evalSolution (Matrix & sField, const Vector & locSol, const int * , int , bool) const virtual
Evaluates the primary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector in DOF-order
The number of visualization points is the same as the order of the Lagrange elements by default.
Reimplemented from ASMs1D.
References evalSolution().
evalSolution() [7/9]
bool ASMs1D::evalSolution
Evaluates the primary solution field at all visualization points.
Parameters
[out] sField Solution field
[in] locSol Solution vector in DOF-order
[in] npe Number of visualization nodes over each knot span
Referenced by evalSolution().
evalSolution() [8/9]
bool ASMs1DLag::evalSolution (Matrix & sField, const Vector & locSol, const RealArray * , bool , int , int) const virtual
Evaluates the primary solution field at the nodal points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
Reimplemented from ASMs1D.
References ASMbase::nnod, and ASMLagBase::nodalField().
evalSolution() [9/9]
bool ASMs1D::evalSolution
Evaluates the primary solution field at the given points.
Parameters
[out] sField Solution field
[in] locSol Solution vector local to current patch
[in] gpar Parameter values of the result sampling points
[in] deriv Derivative order to return
References ASMs1D::generateOrientedFEModel().
generateOrientedFEModel()
bool ASMs1DLag::generateOrientedFEModel (const Vec3 & Zaxis) virtual
Generates a beam finite element model for the patch.
Parameters
[in] Zaxis Vector defining a point in the local XZ-plane
Reimplemented from ASMs1D.
Reimplemented in ASMu1DLag.
References ASMLagBase::coord, createMNPC(), ASMs1D::curv, ASMbase::firstEl, ASMbase::gEl, ASMs1D::getGridParameters(), ASMbase::gNod, ASMs1D::initLocalElementAxes(), ASMLagBase::myCoord, ASMs1D::myCS, ASMbase::myMLGE, ASMbase::myMLGN, ASMbase::myMNPC, ASMs1D::myT, ASMbase::nel, ASMbase::nf, ASMbase::nnod, ASMbase::nsd, nx, p1, and ASMs1D::proj.
getCoord()
Vec3 ASMs1DLag::getCoord (size_t inod) const virtual
Returns the global coordinates for the given node.
Parameters
[in] inod 1-based node index local to current patch
Reimplemented from ASMs1D.
References ASMLagBase::coord.
getElementCoordinates()
bool ASMs1DLag::getElementCoordinates (Matrix & X, int iel, bool = true) const virtual
Returns a matrix with nodal coordinates for an element.
Parameters
[out] X 3 \(\times\)n-matrix, where n is the number of nodes in one element
[in] iel Element index
Reimplemented from ASMs1D.
References ASMLagBase::coord, utl::matrix< T >::fillColumn(), ASMbase::MNPC, ASMbase::nsd, p1, and utl::matrix< T >::resize().
Referenced by evalSolution(), ASMs1DSpec::evalSolution(), integrate(), and ASMs1DSpec::integrate().
getNodalCoordinates()
void ASMs1DLag::getNodalCoordinates (Matrix & X, bool = false) const virtual
Returns a matrix with all nodal coordinates within the patch.
Parameters
[out] X 3 \(\times\)n-matrix, where n is the number of nodes in the patch
Reimplemented from ASMs1D.
References ASMLagBase::coord, utl::matrix< T >::fillColumn(), ASMbase::nsd, and utl::matrix< T >::resize().
getSize()
bool ASMs1D::getSize
Returns the number of nodal points in each parameter direction.
Parameters
[out] n1 Number of nodes in first (u) direction
[out] n2 Number of nodes in second (v) direction (always zero)
[out] n3 Number of nodes in third (w) direction (always zero)
[in] basis Which basis to return size parameters for (mixed methods)
References ASMs1D::nodeSets.
integrate() [1/2]
bool ASMs1DLag::integrate (Integrand & integrand, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates an integral over the interior patch domain.
Parameters
integrand Object with problem-specific data and methods
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMs1D.
Reimplemented in ASMs1DSpec.
References FiniteElement::age, GlobalIntegral::assemble(), Vec4::assign(), utl::matrix< T >::cols(), Lagrange::computeBasis(), LocalIntegral::destruct(), FiniteElement::detJxW, Tensor::diag(), FiniteElement::dNdX, Integrand::ELEMENT_CORNERS, ASMs1D::elmCS, ASMstruct::empty(), Integrand::evalInt(), Integrand::finalizeElement(), ASMbase::firstEl, ASMbase::firstIp, GaussQuadrature::getCoord(), getElementCoordinates(), ASMs1D::getElementNodalRotations(), getEndPoints(), ASMs1D::getGridParameters(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), ASMbase::getNoGaussPt(), Integrand::getReducedIntegration(), GaussQuadrature::getWeight(), FiniteElement::h, ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElement(), utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, FiniteElement::N, ASMbase::nel, Integrand::NO_DERIVATIVES, Integrand::NODAL_ROTATIONS, p1, Integrand::reducedInt(), LocalIntegral::ref(), TimeDomain::t, FiniteElement::Te, FiniteElement::Tn, ItgPoint::u, FiniteElement::XC, ItgPoint::xi, and FiniteElement::Xn.
integrate() [2/2]
bool ASMs1DLag::integrate (Integrand & integrand, int lIndex, GlobalIntegral & glbInt, const TimeDomain & time) virtual
Evaluates a boundary integral over a patch end.
Parameters
integrand Object with problem-specific data and methods
[in] lIndex Local index of the end point
glbInt The integrated quantity
[in] time Parameters for nonlinear/time-dependent simulations
Reimplemented from ASMs1D.
Reimplemented in ASMs1DSpec.
References FiniteElement::age, GlobalIntegral::assemble(), utl::matrix< T >::cols(), Lagrange::computeBasis(), ASMs1D::curv, LocalIntegral::destruct(), Tensor::diag(), FiniteElement::dNdX, Integrand::ELEMENT_CORNERS, ASMs1D::elmCS, ASMstruct::empty(), Integrand::evalBou(), ASMbase::firstBp, ASMbase::firstEl, getElementCoordinates(), ASMs1D::getElementNodalRotations(), getEndPoints(), Integrand::getIntegrandType(), Integrand::getLocalIntegral(), FiniteElement::h, ItgPoint::idx, ItgPoint::iel, ItgPoint::iGP, Integrand::initElementBou(), utl::Jacobian(), ASMbase::MLGE, ASMbase::MNPC, FiniteElement::N, ASMbase::nel, Integrand::NO_DERIVATIVES, Integrand::NODAL_ROTATIONS, p1, LocalIntegral::ref(), Integrand::setNeumannOrder(), TimeDomain::t, FiniteElement::Te, FiniteElement::Tn, ItgPoint::u, Vec3::x, FiniteElement::XC, ItgPoint::xi, and FiniteElement::Xn.
tesselate()
bool ASMs1DLag::tesselate (ElementBlock & grid, const int *) const virtual
Creates a line element model of this patch for visualization.
Parameters
[out] grid The generated line grid
Note
The number of element nodes must be set in grid on input.
Reimplemented from ASMs1D.
Reimplemented in ASMu1DLag.
References ASMLagBase::coord, ElementBlock::getNoNodes(), nx, p1, ElementBlock::resize(), ElementBlock::setCoor(), ElementBlock::setElmId(), and ElementBlock::setNode().
updateCoords()
bool ASMs1DLag::updateCoords (const Vector & displ) virtual
Updates the nodal coordinates for this patch.
Parameters
[in] displ Incremental displacements to update the coordinates with
Reimplemented from ASMs1D.
References ASMbase::nsd, ASMbase::shareFE, and ASMLagBase::updateCoords().
The documentation for this class was generated from the following files:
src/ASM/ASMs1DLag.h
src/ASM/ASMs1DLag.C