IFEM: EqualOrderOperators::Residual Class Reference
EqualOrderOperators::Residual Class Reference
Common weak residual operators using equal-ordered discretizations.
#include <EqualOrderOperators.h>
Static Public Member Functions
static void Advection (Vector &EV, const FiniteElement &fe, const Vec3 &AC, const Tensor &g, double scale=1.0, int basis=1)
Compute an advection term.
static void Convection (Vector &EV, const FiniteElement &fe, const Vec3 &U, const Tensor &dUdX, const Vec3 &UC, double scale, WeakOperators::ConvectionForm form=WeakOperators::CONVECTIVE, int basis=1)
Compute a convection term in a residual vector.
static void Divergence (Vector &EV, const FiniteElement &fe, const Tensor &dUdX, double scale=1.0, size_t basis=1)
Compute a divergence term in a residual vector.
static void Gradient (Vector &EV, const FiniteElement &fe, double scale=1.0, int basis=1)
Compute a gradient term.
static void Laplacian (Vector &EV, const FiniteElement &fe, const Vec3 &dUdX, double scale=1.0, int basis=1)
Compute a laplacian term in a residual vector.
static void Laplacian (Vector &EV, const FiniteElement &fe, const Tensor &dUdX, double scale=1.0, bool stress=false, int basis=1)
Compute a laplacian term in a residual vector.
Detailed Description
Common weak residual operators using equal-ordered discretizations.
Member Function Documentation
Advection()
void EqualOrderOperators::Residual::Advection (Vector & EV, const FiniteElement & fe, const Vec3 & AC, const Tensor & g, double scale = 1.0, int basis = 1) static
Compute an advection term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] AC Advecting field
[in] g Advected field gradient
[in] scale Scaling factor for contribution
[in] basis Basis to use
References utl::vector< T >::add(), FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::detJxW, and FiniteElement::grad().
Convection()
void EqualOrderOperators::Residual::Convection (Vector & EV, const FiniteElement & fe, const Vec3 & U, const Tensor & dUdX, const Vec3 & UC, double scale, WeakOperators::ConvectionForm form = WeakOperators::CONVECTIVE, int basis = 1) static
Compute a convection term in a residual vector.
Parameters
EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] U Advected field
[in] dUdX Advected field gradient
[in] UC Advecting field
[in] scale Scaling factor for contribution
[in] form Which form of the convective term to use
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, FiniteElement::grad(), and utl::vector< T >::size().
Divergence()
void EqualOrderOperators::Residual::Divergence (Vector & EV, const FiniteElement & fe, const Tensor & dUdX, double scale = 1.0, size_t basis = 1) static
Compute a divergence term in a residual vector.
Parameters
EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] dUdX Gradient of field
[in] scale Scaling factor for contribution
[in] basis Basis to use
References utl::vector< T >::add(), FiniteElement::basis(), FiniteElement::detJxW, and Tensor::trace().
Gradient()
void EqualOrderOperators::Residual::Gradient (Vector & EV, const FiniteElement & fe, double scale = 1.0, int basis = 1) static
Compute a gradient term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
References utl::vector< T >::add(), utl::matrix< T >::cols(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), and FiniteElement::grad().
Laplacian() [1/2]
void EqualOrderOperators::Residual::Laplacian (Vector & EV, const FiniteElement & fe, const Tensor & dUdX, double scale = 1.0, bool stress = false, int basis = 1) static
Compute a laplacian term in a residual vector.
Parameters
EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] dUdX Current solution gradient
[in] scale Scaling factor for contribution
[in] stress Whether to add extra stress formulation terms
[in] basis Basis to use
References utl::vector< T >::add(), utl::matrix< T >::cols(), FiniteElement::detJxW, FiniteElement::grad(), utl::matrix< T >::multiply(), and Tensor::transpose().
Laplacian() [2/2]
void EqualOrderOperators::Residual::Laplacian (Vector & EV, const FiniteElement & fe, const Vec3 & dUdX, double scale = 1.0, int basis = 1) static
Compute a laplacian term in a residual vector.
Parameters
EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] dUdX Current solution gradient
[in] scale Scaling factor for contribution
[in] basis Basis to use
References utl::matrix< T >::cols(), FiniteElement::detJxW, FiniteElement::grad(), utl::matrix< T >::multiply(), and Vec3::ptr().
The documentation for this class was generated from the following files:
Apps/Common/EqualOrderOperators.h
Apps/Common/EqualOrderOperators.C