IFEM: TimeIntegration::SIMImplicitLMM< Solver > Class Template Reference
TimeIntegration::SIMImplicitLMM< Solver > Class Template Reference
Implicit multi-step time integration for SIM classes.
#include <SIMImplicitLMM.h>
Classes
class LMMNonLinSIM
Specialized nonlinear solver for implicit LMM methods.
Public Member Functions
SIMImplicitLMM (Solver &solv, Method type, bool=false, const std::string &solField="")
Constructor.
~SIMImplicitLMM ()
Destructor frees up the load vectors.
const ProcessAdm & getProcessAdm () const
Returns the parallel process administrator.
bool solveStep (TimeStep &tp)
Computes the solution for the current time step.
bool advanceStep (TimeStep &tp)
Advances the time step one step forward.
bool saveModel (char *fileName, int &geoBlk, int &nBlock)
Opens a new VTF-file and writes the model geometry to it.
bool saveStep (const TimeStep &tp, int &nBlock)
Saves the converged results of a given time step to VTF file.
void registerFields (DataExporter &exporter)
Registers fields for output to a data exporter.
bool serialize (std::map< std::string, std::string > &data)
Serialize internal state for restarting purposes.
bool deSerialize (const std::map< std::string, std::string > &data)
Set internal state from a serialized state.
Protected Attributes
Solver & solver
Reference to simulator.
LMMNonLinSIM nSim
Nonlinear solver.
std::vector< SystemVector * > loads
Unscaled load vectors.
int order
Order of method.
const std::string fieldName
Name of primary solution fields (for ICs)
bool hasICs = false
If true, start with full order.
Detailed Description
template<class Solver>
class TimeIntegration::SIMImplicitLMM< Solver >
Implicit multi-step time integration for SIM classes.
Template can be instanced over any simulator implementing ISolver and which derives from SIMbase.
Constructor & Destructor Documentation
SIMImplicitLMM()
template<class Solver > TimeIntegration::SIMImplicitLMM< Solver >::SIMImplicitLMM (Solver & solv, Method type, bool = false, const std::string & solField = "") inline
Constructor.
Parameters
solv The simulator to do time stepping for
type The time integration scheme to use
solField Name of primary solution fields (for ICs)
References TimeIntegration::AM2, TimeIntegration::AM3, TimeIntegration::AM4, TimeIntegration::SIMImplicitLMM< Solver >::loads, and TimeIntegration::SIMImplicitLMM< Solver >::order.
Member Function Documentation
advanceStep()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::advanceStep (TimeStep & tp) inline
Advances the time step one step forward.
References TimeDomain::dt, TimeIntegration::SIMImplicitLMM< Solver >::fieldName, TimeIntegration::SIMImplicitLMM< Solver >::hasICs, TimeIntegration::SIMImplicitLMM< Solver >::loads, TimeIntegration::SIMImplicitLMM< Solver >::order, TimeIntegration::SIMImplicitLMM< Solver >::solver, TimeStep::step, TimeDomain::t, and TimeStep::time.
deSerialize()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::deSerialize (const std::map< std::string, std::string > & data) inline
Set internal state from a serialized state.
Parameters
[in] data Container for serialized data
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
getProcessAdm()
template<class Solver > const ProcessAdm& TimeIntegration::SIMImplicitLMM< Solver >::getProcessAdm () const inline
Returns the parallel process administrator.
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
registerFields()
template<class Solver > void TimeIntegration::SIMImplicitLMM< Solver >::registerFields (DataExporter & exporter) inline
Registers fields for output to a data exporter.
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
saveModel()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::saveModel (char * fileName, int & geoBlk, int & nBlock) inline
Opens a new VTF-file and writes the model geometry to it.
Parameters
[in] fileName File name used to construct the VTF-file name from
[out] geoBlk Running geometry block counter
[out] nBlock Running result block counter
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
saveStep()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::saveStep (const TimeStep & tp, int & nBlock) inline
Saves the converged results of a given time step to VTF file.
Parameters
[in] tp Time stepping parameters
[in] nBlock Running VTF block counter
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
serialize()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::serialize (std::map< std::string, std::string > & data) inline
Serialize internal state for restarting purposes.
Parameters
data Container for serialized data
References TimeIntegration::SIMImplicitLMM< Solver >::solver.
solveStep()
template<class Solver > bool TimeIntegration::SIMImplicitLMM< Solver >::solveStep (TimeStep & tp) inline
Computes the solution for the current time step.
References TimeDomain::dt, SIMsolution::getSolution(), TimeIntegration::SIMImplicitLMM< Solver >::hasICs, MultiStepSIM::initSol(), TimeIntegration::SIMImplicitLMM< Solver >::loads, TimeIntegration::SIMImplicitLMM< Solver >::nSim, TimeIntegration::SIMImplicitLMM< Solver >::order, TimeIntegration::SIMImplicitLMM< Solver >::LMMNonLinSIM::setCoefs(), TimeIntegration::SIMImplicitLMM< Solver >::solver, NonLinSIM::solveStep(), TimeStep::step, SIMsolution::theSolutions(), and TimeStep::time.
The documentation for this class was generated from the following file:
Apps/Common/SIMImplicitLMM.h