IFEM: SplineFields2D Class Reference
SplineFields2D Class Reference
Class for spline-based finite element vector fields in 2D.
#include <SplineFields2D.h>
Public Member Functions
SplineFields2D (const ASMs2D *patch, const RealArray &v, char basis=1, int nf=0, const char *name=nullptr)
The constructor sets the number of space dimensions and fields.
SplineFields2D (const Go::SplineSurface *srf, const RealArray &v, int ncmp, const char *name=nullptr)
Construct directly from surface.
virtual ~SplineFields2D ()
Empty destructor.
virtual bool valueNode (size_t node, Vector &vals) const
Computes the value in a given node/control point.
virtual bool valueFE (const ItgPoint &x, Vector &vals) const
Computes the value at a given local coordinate.
virtual bool valueCoor (const Vec4 &x, Vector &vals) const
Computes the value at a given global coordinate.
virtual bool gradFE (const ItgPoint &x, Matrix &grad) const
Computes the gradient for a given local coordinate.
virtual bool hessianFE (const ItgPoint &x, Matrix3D &H) const
Computes the hessian for a given local coordinate.
Public Member Functions inherited from Fields
virtual ~Fields ()
Empty destructor.
unsigned char getNoFields () const
Returns the number of field components.
size_t getNoElm () const
Returns the number of elements.
size_t getNoNodes () const
Returns the number of nodal/control points.
const char * getFieldName () const
Returns the name of field.
virtual bool gradCoor (const Vec4 &x, Matrix &grad) const
Computes the gradient for a given global coordinate.
Protected Attributes
const Go::SplineSurface * basis
Spline basis description.
const Go::SplineSurface * surf
Spline geometry description.
Protected Attributes inherited from Fields
unsigned char nf
Number of field components.
size_t nelm
Number of elements/knot-spans.
size_t nno
Number of nodes/control points.
std::string fname
Name of the field.
Vector values
Field values.
Private Attributes
unsigned char nsd
Number of space dimensions.
Additional Inherited Members
Static Public Member Functions inherited from Fields
static Fields * create (const ASMbase *pch, const RealArray &v, char basis=1, int nf=0, const char *name=nullptr)
Creates a dynamically allocated field object.
Protected Member Functions inherited from Fields
Fields (const char *name=nullptr)
The constructor sets the field name.
Detailed Description
Class for spline-based finite element vector fields in 2D.
This class implements the methods required to evaluate a 2D spline vector field at a given point in parametrical or physical coordinates.
Constructor & Destructor Documentation
SplineFields2D() [1/2]
SplineFields2D::SplineFields2D (const ASMs2D * patch, const RealArray & v, char basis = 1, int nf = 0, const char * name = nullptr)
The constructor sets the number of space dimensions and fields.
Parameters
[in] patch The spline patch on which the field is to be defined
[in] v Array of control point field values
[in] basis Basis to use from patch
[in] nf Number of components in field
[in] name Name of spline field
References basis, utl::vector< T >::begin(), ASMbase::getNoFields(), ASMs2D::getNoNodes(), ASMbase::getNoSpaceDim(), Fields::nelm, Fields::nf, Fields::nno, nsd, utl::vector< T >::resize(), and Fields::values.
SplineFields2D() [2/2]
SplineFields2D::SplineFields2D (const Go::SplineSurface * srf, const RealArray & v, int ncmp, const char * name = nullptr)
Construct directly from surface.
Parameters
[in] srf The spline surface to use
[in] v Array of control point field values
[in] ncmp Number of field components
[in] name Name of spline field
References Fields::nf, nsd, and Fields::values.
Member Function Documentation
gradFE()
bool SplineFields2D::gradFE (const ItgPoint & x, Matrix & grad) const virtual
Computes the gradient for a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] grad Gradient of solution in a given local coordinate
Implements Fields.
References basis, utl::matrixBase< T >::empty(), SplineField::evalBasis(), SplineField::evalMapping(), utl::gather(), utl::matrix< T >::multiply(), Fields::nf, nsd, surf, and Fields::values.
hessianFE()
bool SplineFields2D::hessianFE (const ItgPoint & x, Matrix3D & H) const virtual
Computes the hessian for a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] H Hessian of solution in a given local coordinate
Reimplemented from Fields.
References basis, SplineField::evalBasis(), SplineField::evalMapping(), utl::gather(), utl::matrix3d< T >::multiply(), Fields::nf, nsd, surf, and Fields::values.
valueCoor()
bool SplineFields2D::valueCoor (const Vec4 & x, Vector & vals) const virtual
Computes the value at a given global coordinate.
Parameters
[in] x Global/physical coordinate for point
[out] vals Values in given physical coordinate
Reimplemented from Fields.
References surf, Vec4::u, valueFE(), Vec3::x, Vec3::y, and Vec3::z.
valueFE()
bool SplineFields2D::valueFE (const ItgPoint & x, Vector & vals) const virtual
Computes the value at a given local coordinate.
Parameters
[in] x Local coordinate of evaluation point
[out] vals Values in local point in given element
Implements Fields.
References basis, utl::gather(), utl::matrix< T >::multiply(), Fields::nf, ASMs2D::scatterInd(), ItgPoint::u, ItgPoint::v, and Fields::values.
Referenced by valueCoor().
valueNode()
bool SplineFields2D::valueNode (size_t node, Vector & vals) const virtual
Computes the value in a given node/control point.
Parameters
[in] node Node number
[out] vals Node values
Reimplemented from Fields.
References utl::vector< T >::fill(), Fields::nf, Fields::nno, utl::vector< T >::ptr(), utl::vector< T >::resize(), and Fields::values.
The documentation for this class was generated from the following files:
src/ASM/SplineFields2D.h
src/ASM/SplineFields2D.C