IFEM: PiolaOperators Class Reference
PiolaOperators Class Reference
Common operators using Piola mapped discretizations.
#include <PiolaOperators.h>
Classes
class Residual
Common weak residual operators using div-compatible discretizations.
class Weak
Common weak operators using Piola mapped discretizations.
Static Public Member Functions
static void Copy (Matrices &EM, const FiniteElement &fe, const std::array< std::array< int, 3 >, 3 > &idx, const Matrix &A)
Add the full Piola operator to the blocks.
static void Copy (Vectors &EV, const FiniteElement &fe, const std::array< int, 3 > &idx, const RealArray &V)
Add the full Piola vector to the blocks.
Detailed Description
Common operators using Piola mapped discretizations.
The operators use the block ordering used in the BlockElmMats class.
Member Function Documentation
Copy() [1/2]
void PiolaOperators::Copy (Matrices & EM, const FiniteElement & fe, const std::array< std::array< int, 3 >, 3 > & idx, const Matrix & A) static
Add the full Piola operator to the blocks.
Parameters
EM Vector of block matrices
fe Finite element information
idx Vector block indices
A Piola operator to add
References FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::dNdX, utl::matrix< T >::extractBlock(), and utl::vector< T >::size().
Referenced by PiolaOperators::Weak::Advection(), PiolaOperators::Weak::Convection(), PiolaOperators::Residual::Convection(), PiolaOperators::Residual::Gradient(), PiolaOperators::Weak::Laplacian(), PiolaOperators::Residual::Laplacian(), PiolaOperators::Weak::Mass(), and PiolaOperators::Weak::Source().
Copy() [2/2]
void PiolaOperators::Copy (Vectors & EV, const FiniteElement & fe, const std::array< int, 3 > & idx, const RealArray & V) static
Add the full Piola vector to the blocks.
Parameters
EV Vector of block vectors
fe Finite element information
idx Vector block indices
V Piola vector to add
References FiniteElement::basis(), utl::matrix< T >::cols(), FiniteElement::dNdX, and utl::vector< T >::size().
The documentation for this class was generated from the following files:
Apps/Common/PiolaOperators.h
Apps/Common/PiolaOperators.C