IFEM: EqualOrderOperators::Weak Class Reference
EqualOrderOperators::Weak Class Reference
Common weak operators using equal-ordered discretizations.
#include <EqualOrderOperators.h>
Static Public Member Functions
static void Advection (Matrix &EM, const FiniteElement &fe, const Vec3 &AC, double scale=1.0, WeakOperators::ConvectionForm form=WeakOperators::CONVECTIVE, int basis=1)
Compute an advection term.
static void Convection (Matrix &EM, const FiniteElement &fe, const Vec3 &U, const Tensor &dUdX, double scale, WeakOperators::ConvectionForm form=WeakOperators::CONVECTIVE, int basis=1)
Compute a (nonlinear) convection term.
static void Divergence (Matrix &EM, const FiniteElement &fe, double scale=1.0, int basis=1, int tbasis=1)
Compute a divergence term.
static void Divergence (Vector &EV, const FiniteElement &fe, const Vec3 &D, double scale=1.0, int basis=1)
Compute a divergence term.
static void Gradient (Matrix &EM, const FiniteElement &fe, double scale=1.0, int basis=1, int tbasis=1)
Compute a gradient term for a (potentially mixed) vector/scalar field.
static void Laplacian (Matrix &EM, const FiniteElement &fe, double scale=1.0, bool stress=false, int basis=1)
Compute a laplacian.
static void Stress (Matrix &EM, const FiniteElement &fe, double scale=1.0, int basis=1)
Compute a stress operator.
static void LaplacianCoeff (Matrix &EM, const Matrix &K, const FiniteElement &fe, double scale=1.0, int basis=1)
Compute a heteregenous coefficient laplacian.
static void ItgConstraint (Matrix &EM, const FiniteElement &fe, double scale=1.0, int basis=1)
Compute an integration constraint.
static void Mass (Matrix &EM, const FiniteElement &fe, double scale=1.0, int basis=1)
Compute a mass term.
static void Source (Vector &EV, const FiniteElement &fe, double scale=1.0, int cmp=1, int basis=1)
Compute a source term.
static void Source (Vector &EV, const FiniteElement &fe, const Vec3 &f, double scale=1.0, int basis=1)
Compute a vector-source term.
Detailed Description
Common weak operators using equal-ordered discretizations.
Member Function Documentation
Advection()
void EqualOrderOperators::Weak::Advection (Matrix & EM, const FiniteElement & fe, const Vec3 & AC, double scale = 1.0, WeakOperators::ConvectionForm form = WeakOperators::CONVECTIVE, int basis = 1) static
Compute an advection term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] AC Advecting field
[in] scale Scaling factor for contribution
[in] form Formulation to use for advection
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), FiniteElement::grad(), utl::matrix< T >::outer_product(), utl::matrix< T >::rows(), and utl::vector< T >::size().
Convection()
void EqualOrderOperators::Weak::Convection (Matrix & EM, const FiniteElement & fe, const Vec3 & U, const Tensor & dUdX, double scale, WeakOperators::ConvectionForm form = WeakOperators::CONVECTIVE, int basis = 1) static
Compute a (nonlinear) convection term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] U Advecting field
[in] dUdX Gradient of advected field
[in] scale Scaling factor for contribution
[in] form Which form of the convective term to use
[in] basis Basis to use
References utl::matrix< T >::add(), FiniteElement::basis(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), FiniteElement::grad(), utl::matrix< T >::outer_product(), utl::matrix< T >::rows(), and utl::vector< T >::size().
Divergence() [1/2]
void EqualOrderOperators::Weak::Divergence (Matrix & EM, const FiniteElement & fe, double scale = 1.0, int basis = 1, int tbasis = 1) static
Compute a divergence term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis for field
[in] tbasis Test function basis
Divergence() [2/2]
void EqualOrderOperators::Weak::Divergence (Vector & EV, const FiniteElement & fe, const Vec3 & D, double scale = 1.0, int basis = 1) static
Compute a divergence term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] D Divergence of field
[in] scale Scaling factor for contribution
[in] basis Test function basis
References utl::matrix< T >::cols(), FiniteElement::detJxW, FiniteElement::grad(), utl::matrix< T >::multiply(), and Vec3::ptr().
Gradient()
void EqualOrderOperators::Weak::Gradient (Matrix & EM, const FiniteElement & fe, double scale = 1.0, int basis = 1, int tbasis = 1) static
Compute a gradient term for a (potentially mixed) vector/scalar field.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis for field
[in] tbasis Test function basis
ItgConstraint()
void EqualOrderOperators::Weak::ItgConstraint (Matrix & EM, const FiniteElement & fe, double scale = 1.0, int basis = 1) static
Compute an integration constraint.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, utl::matrix< T >::rows(), and utl::vector< T >::size().
Referenced by CompatibleOperators::Weak::ItgConstraint().
Laplacian()
void EqualOrderOperators::Weak::Laplacian (Matrix & EM, const FiniteElement & fe, double scale = 1.0, bool stress = false, int basis = 1) static
Compute a laplacian.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] stress Whether to add extra stress formulation terms
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, FiniteElement::grad(), utl::matrix< T >::multiply(), utl::matrix< T >::rows(), and utl::vector< T >::size().
Referenced by CompatibleOperators::Weak::Laplacian().
LaplacianCoeff()
void EqualOrderOperators::Weak::LaplacianCoeff (Matrix & EM, const Matrix & K, const FiniteElement & fe, double scale = 1.0, int basis = 1) static
Compute a heteregenous coefficient laplacian.
Parameters
[out] EM The element matrix to add contribution to
[out] K The coefficient matrix
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
References FiniteElement::detJxW, FiniteElement::grad(), K, and utl::matrix< T >::multiply().
Mass()
void EqualOrderOperators::Weak::Mass (Matrix & EM, const FiniteElement & fe, double scale = 1.0, int basis = 1) static
Compute a mass term.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, utl::matrix< T >::outer_product(), utl::matrix< T >::rows(), and utl::vector< T >::size().
Referenced by CompatibleOperators::Weak::Mass().
Source() [1/2]
void EqualOrderOperators::Weak::Source (Vector & EV, const FiniteElement & fe, const Vec3 & f, double scale = 1.0, int basis = 1) static
Compute a vector-source term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] f Vector with contributions
[in] scale Scaling factor for contribution
[in] basis Basis to use
References utl::vector< T >::add(), FiniteElement::basis(), FiniteElement::detJxW, and utl::vector< T >::size().
Source() [2/2]
void EqualOrderOperators::Weak::Source (Vector & EV, const FiniteElement & fe, double scale = 1.0, int cmp = 1, int basis = 1) static
Compute a source term.
Parameters
[out] EV The element vector to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
[in] cmp Component to add (0 for all)
References utl::vector< T >::add(), FiniteElement::basis(), FiniteElement::detJxW, and utl::vector< T >::size().
Referenced by CompatibleOperators::Weak::Source().
Stress()
void EqualOrderOperators::Weak::Stress (Matrix & EM, const FiniteElement & fe, double scale = 1.0, int basis = 1) static
Compute a stress operator.
Parameters
[out] EM The element matrix to add contribution to
[in] fe The finite element to evaluate for
[in] scale Scaling factor for contribution
[in] basis Basis to use
References FiniteElement::basis(), FiniteElement::detJxW, utl::matrix< T >::getColumn(), FiniteElement::grad(), utl::matrix< T >::outer_product(), utl::matrix< T >::rows(), and utl::vector< T >::size().
The documentation for this class was generated from the following files:
Apps/Common/EqualOrderOperators.h
Apps/Common/EqualOrderOperators.C