IFEM: SplineField Class Reference
SplineField Class Reference
Utility class for spline-based finite element fields.
#include <SplineField.h>
Static Public Member Functions
static bool evalMapping (const Go::SplineSurface &surf, int nsd, const ItgPoint &x, std::vector< int > &ip, Matrix &Xnod, Matrix &Jac, Matrix &dNdX, Matrix3D *d2NdX2=nullptr, Matrix3D *Hess=nullptr)
Evaluate the Jacobian (and Hessian) of the geometry mapping.
static bool evalBasis (const Go::SplineSurface &surf, const ItgPoint &x, std::vector< int > &ip, const Matrix &Xnod, const Matrix &Jac, Matrix &dNdX, Matrix3D *d2NdX2=nullptr, Matrix3D *Hess=nullptr)
Evaluate a basis.
static bool evalMapping (const Go::SplineVolume &vol, const ItgPoint &x, std::vector< int > &ip, Matrix &Xnod, Matrix &Jac, Matrix &dNdX, Matrix3D *d2NdX2=nullptr, Matrix3D *Hess=nullptr)
Evaluate the Jacobian (and Hessian) of the geometry mapping.
static bool evalBasis (const Go::SplineVolume &vol, const ItgPoint &x, std::vector< int > &ip, const Matrix &Xnod, const Matrix &Jac, Matrix &dNdX, Matrix3D *d2NdX2=nullptr, Matrix3D *Hess=nullptr)
Evaluate a basis.
Detailed Description
Utility class for spline-based finite element fields.
This class implements the method to extract the geometry mapping and evaluate a basis.
Member Function Documentation
evalBasis() [1/2]
bool SplineField::evalBasis (const Go::SplineSurface & surf, const ItgPoint & x, std::vector< int > & ip, const Matrix & Xnod, const Matrix & Jac, Matrix & dNdX, Matrix3D * d2NdX2 = nullptr, Matrix3D * Hess = nullptr) static
Evaluate a basis.
Parameters
surf Surface to evaluate for
x Point to evaluate in
ip Vector of basis function indices
Xnod Geometry coefficients in point
Jac Jacobian of geometry mapping in point
dNdX Derivatives of basis functions in point
d2NdX2 Second derivatives of basis functions in point
Hess Hessian of geometry mapping in point
References utl::matrixBase< T >::clear(), SplineUtils::extractBasis(), utl::Hessian(), utl::matrix< T >::multiply(), ASMs2D::scatterInd(), ItgPoint::u, and ItgPoint::v.
Referenced by SplineFields2D::gradFE(), SplineFields2Dmx::gradFE(), SplineFields3D::gradFE(), SplineFields3Dmx::gradFE(), SplineField2D::gradFE(), SplineField3D::gradFE(), SplineField2D::hessianFE(), SplineField3D::hessianFE(), SplineFields2D::hessianFE(), SplineFields2Dmx::hessianFE(), SplineFields3D::hessianFE(), and SplineFields3Dmx::hessianFE().
evalBasis() [2/2]
bool SplineField::evalBasis (const Go::SplineVolume & vol, const ItgPoint & x, std::vector< int > & ip, const Matrix & Xnod, const Matrix & Jac, Matrix & dNdX, Matrix3D * d2NdX2 = nullptr, Matrix3D * Hess = nullptr) static
Evaluate a basis.
Parameters
vol Volume to evaluate for
x Point to evaluate in
ip Vector of basis function indices
Xnod Geometry coefficients in point
Jac Jacobian of geometry mapping in point
dNdX Derivatives of basis functions in point
d2NdX2 Second derivatives of basis functions in point
Hess Hessian of geometry mapping in point
References utl::matrixBase< T >::clear(), SplineUtils::extractBasis(), utl::Hessian(), utl::matrix< T >::multiply(), ASMs3D::scatterInd(), ItgPoint::u, ItgPoint::v, and ItgPoint::w.
evalMapping() [1/2]
bool SplineField::evalMapping (const Go::SplineSurface & surf, int nsd, const ItgPoint & x, std::vector< int > & ip, Matrix & Xnod, Matrix & Jac, Matrix & dNdX, Matrix3D * d2NdX2 = nullptr, Matrix3D * Hess = nullptr) static
Evaluate the Jacobian (and Hessian) of the geometry mapping.
Parameters
surf Surface to evaluate for
nsd Number of spatial dimensions
x Point to evaluate in
ip Vector of basis function indices
Xnod Geometry coefficients in point
Jac Jacobian of geometry mapping in point
dNdX Basis function derivatives in point
d2NdX2 Second derivatives of basis functions in point
Hess Hessian of geometry mapping in point
References SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), utl::Hessian(), utl::Jacobian(), utl::matrix< T >::resize(), ASMs2D::scatterInd(), ItgPoint::u, and ItgPoint::v.
Referenced by SplineFields2D::gradFE(), SplineFields2Dmx::gradFE(), SplineFields3D::gradFE(), SplineFields3Dmx::gradFE(), SplineField2D::gradFE(), SplineField3D::gradFE(), SplineField2D::hessianFE(), SplineField3D::hessianFE(), SplineFields2D::hessianFE(), SplineFields2Dmx::hessianFE(), SplineFields3D::hessianFE(), and SplineFields3Dmx::hessianFE().
evalMapping() [2/2]
bool SplineField::evalMapping (const Go::SplineVolume & vol, const ItgPoint & x, std::vector< int > & ip, Matrix & Xnod, Matrix & Jac, Matrix & dNdX, Matrix3D * d2NdX2 = nullptr, Matrix3D * Hess = nullptr) static
Evaluate the Jacobian (and Hessian) of the geometry mapping.
Parameters
vol Volume to evaluate for
x Point to evaluate in
ip Vector of basis function indices
Xnod Geometry coefficients in point
Jac Jacobian of geometry mapping in point
dNdX Basis function derivatives in point
d2NdX2 Second derivatives of basis functions in point
Hess Hessian of geometry mapping in point
References SplineUtils::extractBasis(), utl::matrix< T >::fillColumn(), utl::Hessian(), utl::Jacobian(), utl::matrix< T >::resize(), ASMs3D::scatterInd(), ItgPoint::u, ItgPoint::v, and ItgPoint::w.
The documentation for this class was generated from the following files:
src/ASM/SplineField.h
src/ASM/SplineField.C