IFEM: HDF5Base Class Reference
HDF5Base Class Reference
Base class for interacting with HDF5 files.
#include <HDF5Base.h>
Public Member Functions
HDF5Base (const std::string &name, const ProcessAdm &adm)
The constructor opens a named HDF5-file.
virtual ~HDF5Base ()
The destructor closes the file.
Protected Member Functions
bool openFile (unsigned int flag)
Opens the HDF5 file.
void closeFile ()
Closes the HDF5 file.
Protected Attributes
std::string m_hdf5_name
The file name of the HDF5 file.
Detailed Description
Base class for interacting with HDF5 files.
Constructor & Destructor Documentation
HDF5Base()
HDF5Base::HDF5Base (const std::string & name, const ProcessAdm & adm)
The constructor opens a named HDF5-file.
Parameters
[in] name The name (without extension) of the data file
[in] adm The process administrator
Member Function Documentation
openFile()
bool HDF5Base::openFile (unsigned int flag) protected
Opens the HDF5 file.
Parameters
[in] flag Mode to open file using
References m_hdf5_name.
Referenced by HDF5Reader::getFieldSize(), HDF5Writer::openFile(), HDF5Reader::read3DArray(), HDF5Restart::readData(), HDF5Reader::readDouble(), HDF5Reader::readString(), HDF5Reader::readVector(), and HDF5Restart::writeData().
The documentation for this class was generated from the following files:
src/Utility/HDF5Base.h
src/Utility/HDF5Base.C