IFEM: src/LinAlg/LAPack.h File Reference
LAPack.h File Reference
LAPack support for various platforms.
#include "BLAS.h"
Functions
void dgecon_ (const char &norm, const int &n, const Real *A, const int &lda, const Real &anorm, Real *rcond, Real *work, int *iwork, int &info)
Estimates the reciprocal of the condition number of the matrix A.
void dgesv_ (const int &n, const int &nrhs, Real *A, const int &lda, int *ipiv, Real *B, const int &ldb, int &info)
Solves the linear equation system A*x=b.
void dgetrf_ (const int &m, const int &n, Real *A, const int &lda, int *ipiv, int &info)
Computes an LU factorization of a general M-by-N matrix A.
void dgetri_ (const int &n, Real *A, const int &lda, int *ipiv, Real *work, const int &lwork, int &info)
Computes the inverse of a matrix based on its LU factorization.
void dgetrs_ (const char &trans, const int &n, const int &nrhs, Real *A, const int &lda, int *ipiv, Real *B, const int &ldb, int &info)
Solves the equation system A*x=b when A is already factorized.
double dlange_ (const char &norm, const int &m, const int &n, const Real *A, const int &lda, Real *work)
Returns a norm of the matrix A.
void dposv_ (const char &uplo, const int &n, const int &nrhs, Real *A, const int &lda, Real *B, const int &ldb, int &info)
Solves the symmetric linear equation system A*x=b.
void dpotrs_ (const char &uplo, const int &n, const int &nrhs, Real *A, const int &lda, Real *B, const int &ldb, int &info)
Solves the symmetric equation system A*x=b for prefactored A.
void dsyev_ (const char &jobz, const char &uplo, const int &n, double *A, const int &lda, double *w, double *work, const int &lwork, int &info)
Solves the standard eigenproblem A*x=(lambda)*x.
void dsyevx_ (const char &jobz, const char &range, const char &uplo, const int &n, Real *a, const int &lda, const Real &vl, const Real &vu, const int &il, const int &iu, const Real &abstol, int &m, Real *w, Real *z, const int &ldz, Real *work, const int &lwork, int *iwork, int *ifail, int &info)
Solves the standard eigenproblem A*x=(lambda)*x.
void dsygvx_ (const int &itype, const char &jobz, const char &range, const char &uplo, const int &n, Real *a, const int &lda, Real *b, const int &ldb, const Real &vl, const Real &vu, const int &il, const int &iu, const Real &abstol, int &m, Real *w, Real *z, const int &ldz, Real *work, const int &lwork, int *iwork, int *ifail, int &info)
Solves the generalized eigenproblem A*x=(lambda)*B*x.
void dgeev_ (const char &jobvl, const char &jobvr, const int &n, Real *a, const int &lda, Real *wr, Real *wi, Real *vl, const int &ldvl, Real *vr, const int &ldvr, Real *work, const int &lwork, int &info)
Solves the non-symmetric eigenproblem A*x=(lambda)*x.
Detailed Description
LAPack support for various platforms.
Date
Jan 10 2016
Author
Knut Morten Okstad / SINTEF
Function Documentation
dgecon_()
void dgecon_ (const char & norm, const int & n, const Real * A, const int & lda, const Real & anorm, Real * rcond, Real * work, int * iwork, int & info)
Estimates the reciprocal of the condition number of the matrix A.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solve().
dgeev_()
void dgeev_ (const char & jobvl, const char & jobvr, const int & n, Real * a, const int & lda, Real * wr, Real * wi, Real * vl, const int & ldvl, Real * vr, const int & ldvr, Real * work, const int & lwork, int & info)
Solves the non-symmetric eigenproblem A*x=(lambda)*x.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solveEigNon().
dgesv_()
void dgesv_ (const int & n, const int & nrhs, Real * A, const int & lda, int * ipiv, Real * B, const int & ldb, int & info)
Solves the linear equation system A*x=b.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by utl::solve(), and DenseMatrix::solve().
dgetrf_()
void dgetrf_ (const int & m, const int & n, Real * A, const int & lda, int * ipiv, int & info)
Computes an LU factorization of a general M-by-N matrix A.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by utl::invert(), and utl::solve().
dgetri_()
void dgetri_ (const int & n, Real * A, const int & lda, int * ipiv, Real * work, const int & lwork, int & info)
Computes the inverse of a matrix based on its LU factorization.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by utl::invert().
dgetrs_()
void dgetrs_ (const char & trans, const int & n, const int & nrhs, Real * A, const int & lda, int * ipiv, Real * B, const int & ldb, int & info)
Solves the equation system A*x=b when A is already factorized.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by utl::solve(), and DenseMatrix::solve().
dlange_()
double dlange_ (const char & norm, const int & m, const int & n, const Real * A, const int & lda, Real * work)
Returns a norm of the matrix A.
This is a FORTRAN-77 function in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solve().
dposv_()
void dposv_ (const char & uplo, const int & n, const int & nrhs, Real * A, const int & lda, Real * B, const int & ldb, int & info)
Solves the symmetric linear equation system A*x=b.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solve().
dpotrs_()
void dpotrs_ (const char & uplo, const int & n, const int & nrhs, Real * A, const int & lda, Real * B, const int & ldb, int & info)
Solves the symmetric equation system A*x=b for prefactored A.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solve().
dsyev_()
void dsyev_ (const char & jobz, const char & uplo, const int & n, double * A, const int & lda, double * w, double * work, const int & lwork, int & info)
Solves the standard eigenproblem A*x=(lambda)*x.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by SymmTensor::principal().
dsyevx_()
void dsyevx_ (const char & jobz, const char & range, const char & uplo, const int & n, Real * a, const int & lda, const Real & vl, const Real & vu, const int & il, const int & iu, const Real & abstol, int & m, Real * w, Real * z, const int & ldz, Real * work, const int & lwork, int * iwork, int * ifail, int & info)
Solves the standard eigenproblem A*x=(lambda)*x.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solveEig().
dsygvx_()
void dsygvx_ (const int & itype, const char & jobz, const char & range, const char & uplo, const int & n, Real * a, const int & lda, Real * b, const int & ldb, const Real & vl, const Real & vu, const int & il, const int & iu, const Real & abstol, int & m, Real * w, Real * z, const int & ldz, Real * work, const int & lwork, int * iwork, int * ifail, int & info)
Solves the generalized eigenproblem A*x=(lambda)*B*x.
This is a FORTRAN-77 subroutine in the LAPack library.
See also
LAPack library documentation.
Referenced by DenseMatrix::solveEig().