IFEM: Apps/Common/MeshUtils.h File Reference
MeshUtils.h File Reference
Various helpers for mesh calculations.
#include "MatVec.h"
Functions
bool MeshUtils::computeAspectRatios (std::vector< double > &elmAspects, const SIMbase &model, const Vector &displacement=Vector())
Compute element aspect ratios for a mesh.
bool MeshUtils::computeMeshSkewness (std::vector< double > &elmSkewness, const SIMbase &model, const Vector &displacement=Vector())
Compute element skewness for a mesh.
Detailed Description
Various helpers for mesh calculations.
Date
Feb 16 2015
Author
Arne Morten Kvarving / SINTEF
Function Documentation
computeAspectRatios()
bool MeshUtils::computeAspectRatios (std::vector< double > & elmAspects, const SIMbase & model, const Vector & displacement = Vector())
Compute element aspect ratios for a mesh.
Parameters
[out] elmAspects The element aspect ratios
[in] model The model holding the mesh
[in] displacement A displacement to apply to mesh coordinates
References aspectRatio(), compute(), and MeshUtils::computeAspectRatios().
Referenced by MeshUtils::computeAspectRatios().
computeMeshSkewness()
bool MeshUtils::computeMeshSkewness (std::vector< double > & elmSkewness, const SIMbase & model, const Vector & displacement = Vector())
Compute element skewness for a mesh.
Parameters
[out] elmSkewness The element skewness values
[in] model The model holding the mesh
[in] displacement A displacement to apply to mesh coordinates
References compute(), MeshUtils::computeMeshSkewness(), and skewness().
Referenced by MeshUtils::computeMeshSkewness().