IFEM: Apps/Common/MeshUtils.C File Reference
MeshUtils.C File Reference
Various mesh quality indicators.
#include "MeshUtils.h"
#include "ASMbase.h"
#include "SIMbase.h"
#include "Vec3.h"
#include "Vec3Oper.h"
Typedefs
typedef double(* CellFunction) (const ASMbase &patch, int iel)
A function calculating a quantity for a single element.
Functions
static bool compute (std::vector< double > &result, const SIMbase &model, const Vector &displacement, CellFunction func)
Function running over mesh cells calling the cellfunction for each element.
static double aspectRatio (const ASMbase &patch, int iel)
Compute the aspect ratio of a cell.
static double skewness (const ASMbase &patch, int iel)
Compute the skewness of a cell.
bool MeshUtils::computeAspectRatios (std::vector< double > &elmAspects, const SIMbase &model, const Vector &displacement=Vector())
Compute element aspect ratios for a mesh.
bool MeshUtils::computeMeshSkewness (std::vector< double > &elmSkewness, const SIMbase &model, const Vector &displacement=Vector())
Compute element skewness for a mesh.
Detailed Description
Various mesh quality indicators.
Date
Feb 16 2015
Author
Arne Morten Kvarving / SINTEF
Function Documentation
aspectRatio()
static double aspectRatio (const ASMbase & patch, int iel) static
Compute the aspect ratio of a cell.
The aspect ratio is defined as the longest edge divided by the shortest edge
References ASMbase::getElementCoordinates(), and ASMbase::getNoSpaceDim().
Referenced by MeshUtils::computeAspectRatios().
computeAspectRatios()
bool MeshUtils::computeAspectRatios (std::vector< double > & elmAspects, const SIMbase & model, const Vector & displacement = Vector())
Compute element aspect ratios for a mesh.
Parameters
[out] elmAspects The element aspect ratios
[in] model The model holding the mesh
[in] displacement A displacement to apply to mesh coordinates
References aspectRatio(), compute(), and MeshUtils::computeAspectRatios().
Referenced by MeshUtils::computeAspectRatios().
computeMeshSkewness()
bool MeshUtils::computeMeshSkewness (std::vector< double > & elmSkewness, const SIMbase & model, const Vector & displacement = Vector())
Compute element skewness for a mesh.
Parameters
[out] elmSkewness The element skewness values
[in] model The model holding the mesh
[in] displacement A displacement to apply to mesh coordinates
References compute(), MeshUtils::computeMeshSkewness(), and skewness().
Referenced by MeshUtils::computeMeshSkewness().
skewness()
static double skewness (const ASMbase & patch, int iel) static
Compute the skewness of a cell.
The skewness measures the deviance from a regular cell in terms of angles
References ASMbase::getElementCoordinates(), ASMbase::getNoSpaceDim(), and Vec3::length().
Referenced by MeshUtils::computeMeshSkewness().