IFEM: ASM Namespace Reference
ASM Namespace Reference
Assembly scope.
Classes
struct Interface
Struct for representing a domain interface.
class InterfaceChecker
Base class to check for internal boundary integrand contributions.
Typedefs
typedef std::pair< std::string, IntVec > NodeSet
Named node set container.
Enumerations
enum Discretization {
SuperElm =-2 , Triangle =-1 , Lagrange = 0 , Spectral = 1 ,
Spline = 2 , SplineC1 = 3 , LRSpline = 4
}
Enum defining the available discretization methods.
enum FinalNormOp { NONE = 0 , ABS = 1 , SQRT = 2 }
Operations to be applied after summing norm element contributions.
enum CachePolicy { NO_CACHE , PRE_CACHE , ON_THE_FLY , FULL_CACHE }
Enum defining available basis function cache policies.
enum BasisType {
GEOMETRY_BASIS = 0 , PROJECTION_BASIS = -1 , PROJECTION_BASIS_2 = -2 , REFINEMENT_BASIS = -3 ,
INTEGRATION_BASIS = -4
}
Enumeration of different basis types.
enum ResultClass {
ANY = 0 , PRIMARY = 1 , SECONDARY = 2 , PROJECTED = 3 ,
ANALYTIC = 4
}
Enum for cathegorization of result quantities.
Functions
bool readMatlab (std::istream &is, IntMat &MNPC, std::vector< Vec3 > &nodes, std::vector< NodeSet > &nodeSets)
Creates a mesh by reading Matlab commands from an input stream.
bool readXML (std::istream &is, IntMat &MNPC, std::vector< Vec3 > &nodes, std::vector< NodeSet > &nodeSets, std::vector< NodeSet > *elemSets=nullptr)
Creates a mesh by reading XML tags from an input stream.
Variables
CachePolicy cachePolicy = ASM::PRE_CACHE
Chosen basis function cache policy.
Detailed Description
Assembly scope.
Enumeration Type Documentation
BasisType
enum ASM::BasisType
Enumeration of different basis types.
Entries should have non-positive values
Enumerator
GEOMETRY_BASIS
Geometry basis.
PROJECTION_BASIS
Projection basis.
PROJECTION_BASIS_2
Second projection basis.
REFINEMENT_BASIS
Refinement basis.
INTEGRATION_BASIS
Integration basis.
CachePolicy
enum ASM::CachePolicy
Enum defining available basis function cache policies.
Enumerator
NO_CACHE
Cache is disabled - calculate on the fly.
PRE_CACHE
Cache basis function values up front, clear on assembly end.
ON_THE_FLY
Cache basis functions on the fly.
FULL_CACHE
Cache basis function values up front.
Function Documentation
readMatlab()
bool ASM::readMatlab (std::istream & is, IntMat & MNPC, std::vector< Vec3 > & nodes, std::vector< NodeSet > & nodeSets)
Creates a mesh by reading Matlab commands from an input stream.
This function reads a matlab file with arrays defining a standard FE mesh. The format corresponds to that of the output method SIMoutput::dumpMatlabGrid.
References utl::readLine().
Referenced by ASMu1DLag::read(), and ASMu2DLag::read().