IFEM: LR Namespace Reference
LR Namespace Reference
Utilities for LR-splines.
Classes
struct RefineData
A struct of data to control the mesh refinement.
Functions
int extendControlPoints (LRSpline *basis, const Vector &v, int nf, int ofs=0)
Expands the basis coefficients of an LR-spline object.
void contractControlPoints (LRSpline *basis, Vector &v, int nf, int ofs=0)
Contracts the basis coefficients of an LR-spline object.
void getGaussPointParameters (const LRSpline *spline, RealArray &uGP, int d, int nGauss, int iel, const double *xi)
Extracts parameter values of the Gauss points in one direction.
void generateThreadGroups (ThreadGroups &threadGroups, const LRSpline *lr, const std::vector< LRSpline * > &addConstraints={})
Generates thread groups for a LR-spline mesh.
void createMNPC (const LR::LRSpline *basis, IntMat &result)
Createss the matrix of nodal point correspondance for a LR-spline.
Detailed Description
Utilities for LR-splines.
Function Documentation
contractControlPoints()
void LR::contractControlPoints (LRSpline * basis, Vector & v, int nf, int ofs = 0)
Contracts the basis coefficients of an LR-spline object.
Parameters
basis The spline object to contact
[out] v Vector containing the extracted basis coefficients
[in] nf Number of fields in the given vector
[in] ofs Offset in vector
Referenced by ASMu2Dmx::refine(), and ASMu3Dmx::refine().
createMNPC()
void LR::createMNPC (const LR::LRSpline * basis, IntMat & result)
Createss the matrix of nodal point correspondance for a LR-spline.
Parameters
[in] basis LR-spline to get nodal point correspondance for
[out] result Matrix of nodal point correspondance for the elements
Referenced by ASMu2D::generateFEMTopology(), ASMu3D::generateFEMTopology(), ASMu2D::getElmNodes(), and ASMu3D::getElmNodes().
extendControlPoints()
int LR::extendControlPoints (LRSpline * basis, const Vector & v, int nf, int ofs = 0)
Expands the basis coefficients of an LR-spline object.
Parameters
basis The spline object to extend
[in] v The vector to append to the basis coefficients
[in] nf Number of fields in the given vector
[in] ofs Offset in vector
Referenced by ASMu2Dmx::refine(), and ASMu3Dmx::refine().
generateThreadGroups()
void LR::generateThreadGroups (ThreadGroups & threadGroups, const LRSpline * lr, const std::vector< LRSpline * > & addConstraints = {})
Generates thread groups for a LR-spline mesh.
Parameters
[out] threadGroups The generated thread groups
[in] lr The LR-spline to generate thread groups for
[in] addConstraints If given, additional constraint bases
Referenced by ASMu2D::generateThreadGroups(), ASMu2Dmx::generateThreadGroups(), ASMu3D::generateThreadGroups(), and ASMu3Dmx::generateThreadGroups().
getGaussPointParameters()
void LR::getGaussPointParameters (const LRSpline * spline, RealArray & uGP, int d, int nGauss, int iel, const double * xi)
Extracts parameter values of the Gauss points in one direction.
Parameters
[in] spline The LR-spline object to get parameter values for
[out] uGP Parameter values in given direction for all points
[in] d Parameter direction (0,1,2)
[in] nGauss Number of Gauss points along a knot-span
[in] iel Element index
[in] xi Dimensionless Gauss point coordinates [-1,1]
Referenced by ASMu2D::getGaussPointParameters().