IFEM: TriangleQuadrature Namespace Reference
TriangleQuadrature Namespace Reference
Triangle quadrature rules.
Functions
const double * getCoord (int n)
Get quadrature point (area-) coordinates in the domain [0,1].
const double * getWeight (int n)
Get quadrature point weights.
Detailed Description
Triangle quadrature rules.
Function Documentation
getCoord()
const double * TriangleQuadrature::getCoord (int n)
Get quadrature point (area-) coordinates in the domain [0,1].
Parameters
[in] n Number of quadrature points
References error(), T1, T3, and T4.
Referenced by ASMs2DTri::integrate().
getWeight()
const double * TriangleQuadrature::getWeight (int n)
Get quadrature point weights.
Parameters
[in] n Number of quadrature points
References error(), W1, W3, and W4.
Referenced by ASMs2DTri::integrate().