IFEM: Chebyshev Namespace Reference
Chebyshev Namespace Reference
Evaluation of Chebyshev polynomials.
Functions
Real evalPol1 (int polnum, Real xi)
Evaluates a 1D Chebyshev polynomial of first kind.
Real evalPol2 (int polnum, Real xi)
Evaluates a 1D Chebyshev polynomial of second kind.
Real evalDer1 (int polnum, Real xi)
Evaluates the first derivative of a 1D Chebyshev polynomial of first kind.
Real evalDer2 (int polnum, Real xi)
Evaluates the first derivative of a 1D Chebyshev polynomial of second kind.
Real eval2Der1 (int polnum, Real xi)
Evaluates the second derivative of a 1D Chebyshev polynomial of first kind.
Detailed Description
Evaluation of Chebyshev polynomials.
Function Documentation
eval2Der1()
Real Chebyshev::eval2Der1 (int polnum, Real xi)
Evaluates the second derivative of a 1D Chebyshev polynomial of first kind.
Parameters
[in] polnum Which polynomial of the basis to evaluate
[in] xi Natural coordinate of the evaluation point
References evalPol1(), and evalPol2().
Referenced by ChebyshevFunc::dderiv().
evalDer1()
Real Chebyshev::evalDer1 (int polnum, Real xi)
Evaluates the first derivative of a 1D Chebyshev polynomial of first kind.
Parameters
[in] polnum Which polynomial of the basis to evaluate
[in] xi Natural coordinate of the evaluation point
References evalPol2().
Referenced by ChebyshevFunc::dderiv(), and ChebyshevFunc::deriv().
evalDer2()
Real Chebyshev::evalDer2 (int polnum, Real xi)
Evaluates the first derivative of a 1D Chebyshev polynomial of second kind.
Parameters
[in] polnum Which polynomial of the basis to evaluate
[in] xi Natural coordinate of the evaluation point
References evalPol1(), and evalPol2().
evalPol1()
Real Chebyshev::evalPol1 (int polnum, Real xi)
Evaluates a 1D Chebyshev polynomial of first kind.
Parameters
[in] polnum Which polynomial of the basis to evaluate
[in] xi Natural coordinate of the evaluation point
Referenced by ChebyshevFunc::dderiv(), ChebyshevFunc::deriv(), eval2Der1(), evalDer2(), and ChebyshevFunc::evaluate().
evalPol2()
Real Chebyshev::evalPol2 (int polnum, Real xi)
Evaluates a 1D Chebyshev polynomial of second kind.
Parameters
[in] polnum Which polynomial of the basis to evaluate
[in] xi Natural coordinate of the evaluation point
Referenced by eval2Der1(), evalDer1(), and evalDer2().