IFEM: src/LinAlg/PETScPCPerm.C File Reference
PETScPCPerm.C File Reference
Permutation for PETSc preconditioners.
#include "PETScPCPerm.h"
#include <iostream>
Macros
#define PetscCall(x) if (x) std::cerr <<"PetscFree failed "<< x << std::endl;
Workaround for nonexisting macro in older PETSc versions.
Functions
PetscErrorCode PCPermCreate (PCPerm **pcperm)
Create the permutated preconditioner.
PetscErrorCode PCPermSetUp (PC pc, IS *perm, Mat A, const char *type)
Configure the permutated preconditioner.
PetscErrorCode PCPermApply (PC pc, Vec x, Vec y)
Apply the permutated preconditioner.
PetscErrorCode PCPermDestroy (PC pc)
Destroy a permutated preconditioner.
Detailed Description
Permutation for PETSc preconditioners.
Date
Jan 15 2010
Author
Runar Holdahl / SINTEF
Function Documentation
PCPermApply()
PetscErrorCode PCPermApply (PC pc, Vec x, Vec y)
Apply the permutated preconditioner.
Parameters
pc Preconditioner to apply
[in] x Vector to apply preconditioner to
[out] y The evaluate preconditioner value
References PCPerm::identity, PCPerm::order, and PCPerm::pc.
Referenced by PETScSolParams::addDirSmoother().
PCPermCreate()
PetscErrorCode PCPermCreate (PCPerm ** pc)
Create the permutated preconditioner.
Parameters
[out] pc Pointer to the preconditioner to create.
References PCPerm::order.
Referenced by PETScSolParams::addDirSmoother().
PCPermDestroy()
PetscErrorCode PCPermDestroy (PC pc)
Destroy a permutated preconditioner.
Parameters
pc Preconditioner to destroy
References PCPerm::pc, and PetscCall.
Referenced by PETScSolParams::addDirSmoother().
PCPermSetUp()
PetscErrorCode PCPermSetUp (PC pc, IS * perm, Mat A, const char * type)
Configure the permutated preconditioner.
Parameters
[out] pc Preconditioner to create
perm The index set describing the ordering
A The matrix to permutate
type type for preconditioner to create
References PCPerm::Aperm, PCPerm::identity, PCPerm::order, and PCPerm::pc.
Referenced by PETScSolParams::addDirSmoother().