IFEM: src/LinAlg/PETScSolParams.C File Reference
PETScSolParams.C File Reference
Linear solver parameters for PETSc.
#include "PETScSolParams.h"
#include "PETScPCPerm.h"
#include "LinSolParams.h"
#include "ProcessAdm.h"
Functions
static std::string AddPrefix (const std::string &prefix, const std::string &data)
Static helper to optionally add a prefix to a PETSc parameter.
static void condSetup (const std::string &prefix, const std::string &petsc_option, const std::string &map_option, const SettingMap &map)
Conditionally add a setting from map to PETsc.
Detailed Description
Linear solver parameters for PETSc.
Date
Mar 10 2016
Author
Arne Morten Kvarving / SINTEF
Function Documentation
condSetup()
static void condSetup (const std::string & prefix, const std::string & petsc_option, const std::string & map_option, const SettingMap & map) static
Conditionally add a setting from map to PETsc.
Parameters
[in] prefix Prefix for petsc setting
[in] petsc_option Name of option in PETsc
[in] map_option Name of option in setting map
[in] map The setting map
References AddPrefix(), SettingMap::getStringValue(), and SettingMap::hasValue().
Referenced by PETScSolParams::setGAMGOptions(), PETScSolParams::setHypreOptions(), and PETScSolParams::setMLOptions().