IFEM: Apps/Common/StabilizationUtils.C File Reference
StabilizationUtils.C File Reference
Various helpers for stabilized formulations.
#include "StabilizationUtils.h"
#include "Vec3Oper.h"
Functions
double StabilizationUtils::getElementSize (const std::vector< Vec3 > &XC, int nsd)
Returns characteristic element size.
double StabilizationUtils::getTauPt (double dt, double mu, const Vector &U, const Matrix &G, const double Ct=2.0, const double Cl=36.0)
Returns stabilization parameters for convection-diffusion equation.
std::pair< double, double > StabilizationUtils::getTauNSPt (double dt, double mu, const Vector &U, const Matrix &G, const double Ct=2.0, const double Cl=36.0)
Computes stabilization parameters for Navier-Stokes equations.
std::pair< double, double > StabilizationUtils::getTauNSALEPt (double dt, double mu, const Vector &U, const Matrix &G, const double Ct=2.0, const double Cl=36.0)
Computes stabilization parameters for Navier-Stokes equations.
Vector StabilizationUtils::getTauPtJac (const Vector &U, const Matrix &G, const double tauM)
Computes variation of stability parameters with respect to velocity.
std::pair< Vector, Vector > StabilizationUtils::getTauNSPtJac (const Vector &U, const Matrix &G, const double tauM, const double &tauC)
Computes variation of stability parameters with respect to velocity.
Detailed Description
Various helpers for stabilized formulations.
Date
Oct 31 2012
Author
Arne Morten Kvarving / SINTEF
Function Documentation
getElementSize()
double StabilizationUtils::getElementSize (const std::vector< Vec3 > & XC, int nsd)
Returns characteristic element size.
Parameters
XC The element corner coordinates
nsd Number of spatial dimensions
The size is taken as the shortest edge length
References StabilizationUtils::getElementSize().
Referenced by StabilizationUtils::getElementSize().
getTauNSALEPt()
std::pair< double, double > StabilizationUtils::getTauNSALEPt (double dt, double mu, const Vector & U, const Matrix & G, const double Ct = 2.0, const double Cl = 36.0)
Computes stabilization parameters for Navier-Stokes equations.
Parameters
[in] dt The timestep size
[in] mu Diffusion/viscosity parameter
[in] U Velocity vector
[in] G The G matrix
[in] Ct VMS parameter
[in] Cl VMS parameter
Returns
Stabilization parameters in integration point
References utl::vector< T >::dot(), StabilizationUtils::getTauNSALEPt(), and StabilizationUtils::getTauPt().
Referenced by StabilizationUtils::getTauNSALEPt().
getTauNSPt()
std::pair< double, double > StabilizationUtils::getTauNSPt (double dt, double mu, const Vector & U, const Matrix & G, const double Ct = 2.0, const double Cl = 36.0)
Computes stabilization parameters for Navier-Stokes equations.
Parameters
[in] dt The timestep size
[in] mu Diffusion/viscosity parameter
[in] U Velocity vector
[in] G The G matrix
[in] Ct VMS parameter
[in] Cl VMS parameter
Returns
Stabilization parameters in integration point
References StabilizationUtils::getTauNSPt(), StabilizationUtils::getTauPt(), and utl::matrix< T >::trace().
Referenced by StabilizationUtils::getTauNSPt().
getTauNSPtJac()
std::pair< Vector, Vector > StabilizationUtils::getTauNSPtJac (const Vector & U, const Matrix & G, const double tauM, const double & tauC)
Computes variation of stability parameters with respect to velocity.
Parameters
[in] U Velocity vector
[in] G The G matrix
[in] tauM Stabilization parameter for momentum
[in] tauC Stabilization parameter for continuity
References StabilizationUtils::getTauNSPtJac(), and StabilizationUtils::getTauPtJac().
Referenced by StabilizationUtils::getTauNSPtJac().
getTauPt()
double StabilizationUtils::getTauPt (double dt, double mu, const Vector & U, const Matrix & G, const double Ct = 2.0, const double Cl = 36.0)
Returns stabilization parameters for convection-diffusion equation.
Parameters
[in] dt The timestep size
[in] mu Diffusion/viscosity parameter
[in] U Velocity vector
[in] G G matrix
[in] Ct VMS parameter
[in] Cl VMS parameter
Stabilization parameter in integration point
References utl::vector< T >::dot(), StabilizationUtils::getTauPt(), and utl::matrixBase< T >::norm2().
Referenced by StabilizationUtils::getTauNSALEPt(), StabilizationUtils::getTauNSPt(), and StabilizationUtils::getTauPt().
getTauPtJac()
Vector StabilizationUtils::getTauPtJac (const Vector & U, const Matrix & G, const double tauM)
Computes variation of stability parameters with respect to velocity.
Parameters
[in] U Velocity vector
[in] G The G matrix
[in] tauM Stabilization parameter for momentum
References StabilizationUtils::getTauPtJac().
Referenced by StabilizationUtils::getTauNSPtJac(), and StabilizationUtils::getTauPtJac().