IFEM: SolverConfigurator< SIMSemi3D< PlaneSolver > > Struct Template Reference
SolverConfigurator< SIMSemi3D< PlaneSolver > > Struct Template Reference
Configuration template for a SIMSemi3D.
#include <SIMSemi3D.h>
Public Member Functions
int setup (SIMSemi3D< PlaneSolver > &simulator, const typename PlaneSolver::SetupProps &props, char *infile)
Configure a SIMSemi3D.
Detailed Description
template<class PlaneSolver>
struct SolverConfigurator< SIMSemi3D< PlaneSolver > >
Configuration template for a SIMSemi3D.
Member Function Documentation
setup()
template<class PlaneSolver > int SolverConfigurator< SIMSemi3D< PlaneSolver > >::setup (SIMSemi3D< PlaneSolver > & simulator, const typename PlaneSolver::SetupProps & props, char * infile) inline
Configure a SIMSemi3D.
Parameters
simulator The simulator to configure
props The setup properties to use
infile The input file to parse
References ConfigureSIM(), SIMSemi3D< PlaneSolver >::getPlane(), SIMSemi3D< PlaneSolver >::getPlanes(), SIMSemi3D< PlaneSolver >::getStartContext(), SIMadmin::opt, and SIMSemi3D< PlaneSolver >::read().
The documentation for this struct was generated from the following file:
Apps/Common/SIMSemi3D.h