name: Build source code documentation

on:
  push:
    tags:
      - "release/*.*"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-docs-pages
  cancel-in-progress: true

jobs:
  build-doc:
    name: Build API documentation

    runs-on: ubuntu-22.04 # Can't use latest since BLAS is not included there

    steps:
      - name: Add the IFEM personal package archive
        run: |
          sudo apt-add-repository -y ppa:ifem/ppa
          sudo apt-get update

      - name: Install IFEM dependencies
        run: |
          sudo apt-get -y install libboost-dev libarpack2-dev libsuperlu-dev libtinyxml2-dev catch2
          sudo apt-get -y install libgotools-core-dev libgotools-trivariate-dev liblrspline1-dev

      - name: Install doxygen
        run: sudo apt-get -y install doxygen graphviz

      - name: Checkout source code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout release tag
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            MY_TAG=${GITHUB_REF_NAME}
          else
            MY_TAG=$(git tag -l --sort=version:refname 'release/*.*' | tail -1)
          fi
          git checkout "$MY_TAG"

      - name: Configure for build
        run: |
          mkdir Release
          cd Release
          cmake .. -DCMAKE_BUILD_TYPE=Release -DIFEM_USE_PETSC=OFF -DIFEM_USE_ISTL=OFF -DIFEM_USE_UMFPACK=OFF

      - name: Build the documentation
        run: |
          cd Release
          make doc
          if [ ! -e doc/html/index.html ]; then
            echo Expected file doc/html/index.html is missing.
            echo \"make doc\" probably failed.
            exit 1
          fi

      - name: Fetch existing documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          git rm -r --ignore-unmatch docs

      - name: Push updates if changed
        run: |
          mv Release/doc/html docs
          git add docs
          if git diff -I "^Generated on .* for IFEM" --quiet --cached HEAD; then
            echo No changes in source code documentation
            git reset --hard HEAD
          else
            git commit -m"Update source code documentation"
            git push origin HEAD
          fi
